// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.models.schemas

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.scalar.core.ExcludeMissing
import com.scalar.core.JsonField
import com.scalar.core.JsonMissing
import com.scalar.core.JsonValue
import com.scalar.core.checkKnown
import com.scalar.core.checkRequired
import com.scalar.core.toImmutable
import com.scalar.errors.ScalarInvalidDataException
import java.util.Collections
import java.util.Objects
import kotlin.jvm.optionals.getOrNull

class Schema
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val uid: JsonField<String>,
    private val title: JsonField<String>,
    private val description: JsonField<String>,
    private val slug: JsonField<String>,
    private val namespace: JsonField<String>,
    private val isPrivate: JsonField<Boolean>,
    private val versions: JsonField<List<ManagedSchemaVersion>>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("uid") @ExcludeMissing uid: JsonField<String> = JsonMissing.of(),
        @JsonProperty("title") @ExcludeMissing title: JsonField<String> = JsonMissing.of(),
        @JsonProperty("description")
        @ExcludeMissing
        description: JsonField<String> = JsonMissing.of(),
        @JsonProperty("slug") @ExcludeMissing slug: JsonField<String> = JsonMissing.of(),
        @JsonProperty("namespace") @ExcludeMissing namespace: JsonField<String> = JsonMissing.of(),
        @JsonProperty("isPrivate") @ExcludeMissing isPrivate: JsonField<Boolean> = JsonMissing.of(),
        @JsonProperty("versions")
        @ExcludeMissing
        versions: JsonField<List<ManagedSchemaVersion>> = JsonMissing.of(),
    ) : this(uid, title, description, slug, namespace, isPrivate, versions, mutableMapOf())

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun uid(): String = uid.getRequired("uid")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun title(): String = title.getRequired("title")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun description(): String = description.getRequired("description")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun slug(): String = slug.getRequired("slug")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun namespace(): String = namespace.getRequired("namespace")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun isPrivate(): Boolean = isPrivate.getRequired("isPrivate")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun versions(): List<ManagedSchemaVersion> = versions.getRequired("versions")

    /**
     * Returns the raw JSON value of [uid].
     *
     * Unlike [uid], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("uid") @ExcludeMissing fun _uid(): JsonField<String> = uid

    /**
     * Returns the raw JSON value of [title].
     *
     * Unlike [title], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("title") @ExcludeMissing fun _title(): JsonField<String> = title

    /**
     * Returns the raw JSON value of [description].
     *
     * Unlike [description], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("description") @ExcludeMissing fun _description(): JsonField<String> = description

    /**
     * Returns the raw JSON value of [slug].
     *
     * Unlike [slug], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("slug") @ExcludeMissing fun _slug(): JsonField<String> = slug

    /**
     * Returns the raw JSON value of [namespace].
     *
     * Unlike [namespace], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("namespace") @ExcludeMissing fun _namespace(): JsonField<String> = namespace

    /**
     * Returns the raw JSON value of [isPrivate].
     *
     * Unlike [isPrivate], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("isPrivate") @ExcludeMissing fun _isPrivate(): JsonField<Boolean> = isPrivate

    /**
     * Returns the raw JSON value of [versions].
     *
     * Unlike [versions], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("versions")
    @ExcludeMissing
    fun _versions(): JsonField<List<ManagedSchemaVersion>> = versions

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [Schema].
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .title()
         * .description()
         * .slug()
         * .namespace()
         * .isPrivate()
         * .versions()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [Schema]. */
    class Builder internal constructor() {

        private var uid: JsonField<String>? = null
        private var title: JsonField<String>? = null
        private var description: JsonField<String>? = null
        private var slug: JsonField<String>? = null
        private var namespace: JsonField<String>? = null
        private var isPrivate: JsonField<Boolean>? = null
        private var versions: JsonField<MutableList<ManagedSchemaVersion>>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(schema: Schema) = apply {
            uid = schema.uid
            title = schema.title
            description = schema.description
            slug = schema.slug
            namespace = schema.namespace
            isPrivate = schema.isPrivate
            versions = schema.versions.map { it.toMutableList() }
            additionalProperties = schema.additionalProperties.toMutableMap()
        }

        fun uid(uid: String) = uid(JsonField.of(uid))

        /**
         * Sets [Builder.uid] to an arbitrary JSON value.
         *
         * You should usually call [Builder.uid] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun uid(uid: JsonField<String>) = apply { this.uid = uid }

        fun title(title: String) = title(JsonField.of(title))

        /**
         * Sets [Builder.title] to an arbitrary JSON value.
         *
         * You should usually call [Builder.title] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun title(title: JsonField<String>) = apply { this.title = title }

        fun description(description: String) = description(JsonField.of(description))

        /**
         * Sets [Builder.description] to an arbitrary JSON value.
         *
         * You should usually call [Builder.description] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun description(description: JsonField<String>) = apply { this.description = description }

        fun slug(slug: String) = slug(JsonField.of(slug))

        /**
         * Sets [Builder.slug] to an arbitrary JSON value.
         *
         * You should usually call [Builder.slug] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun slug(slug: JsonField<String>) = apply { this.slug = slug }

        fun namespace(namespace: String) = namespace(JsonField.of(namespace))

        /**
         * Sets [Builder.namespace] to an arbitrary JSON value.
         *
         * You should usually call [Builder.namespace] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun namespace(namespace: JsonField<String>) = apply { this.namespace = namespace }

        fun isPrivate(isPrivate: Boolean) = isPrivate(JsonField.of(isPrivate))

        /**
         * Sets [Builder.isPrivate] to an arbitrary JSON value.
         *
         * You should usually call [Builder.isPrivate] with a well-typed [Boolean] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun isPrivate(isPrivate: JsonField<Boolean>) = apply { this.isPrivate = isPrivate }

        fun versions(versions: List<ManagedSchemaVersion>) = versions(JsonField.of(versions))

        /**
         * Sets [Builder.versions] to an arbitrary JSON value.
         *
         * You should usually call [Builder.versions] with a well-typed `List<ManagedSchemaVersion>`
         * value instead. This method is primarily for setting the field to an undocumented or not
         * yet supported value.
         */
        fun versions(versions: JsonField<List<ManagedSchemaVersion>>) = apply {
            this.versions = versions.map { it.toMutableList() }
        }

        /**
         * Adds a single [ManagedSchemaVersion] to [versions].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addVersion(version: ManagedSchemaVersion) = apply {
            versions =
                (versions ?: JsonField.of(mutableListOf())).also {
                    checkKnown("versions", it).add(version)
                }
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [Schema].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .title()
         * .description()
         * .slug()
         * .namespace()
         * .isPrivate()
         * .versions()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): Schema =
            Schema(
                checkRequired("uid", uid),
                checkRequired("title", title),
                checkRequired("description", description),
                checkRequired("slug", slug),
                checkRequired("namespace", namespace),
                checkRequired("isPrivate", isPrivate),
                checkRequired("versions", versions).map { it.toImmutable() },
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws ScalarInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): Schema = apply {
        if (validated) {
            return@apply
        }

        uid()
        title()
        description()
        slug()
        namespace()
        isPrivate()
        versions().forEach { it.validate() }
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: ScalarInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (uid.asKnown().isPresent) 1 else 0) +
            (if (title.asKnown().isPresent) 1 else 0) +
            (if (description.asKnown().isPresent) 1 else 0) +
            (if (slug.asKnown().isPresent) 1 else 0) +
            (if (namespace.asKnown().isPresent) 1 else 0) +
            (if (isPrivate.asKnown().isPresent) 1 else 0) +
            (versions.asKnown().getOrNull()?.sumOf { it.validity().toInt() } ?: 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is Schema &&
            uid == other.uid &&
            title == other.title &&
            description == other.description &&
            slug == other.slug &&
            namespace == other.namespace &&
            isPrivate == other.isPrivate &&
            versions == other.versions &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            uid,
            title,
            description,
            slug,
            namespace,
            isPrivate,
            versions,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "Schema{uid=$uid, title=$title, description=$description, slug=$slug, namespace=$namespace, isPrivate=$isPrivate, versions=$versions, additionalProperties=$additionalProperties}"
}
