// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.google.errorprone.annotations.MustBeClosed
import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.accessGroups.AccessGroupCreateParams
import com.scalar.models.accessGroups.AccessGroupCreateResponse
import com.scalar.models.accessGroups.AccessGroupDeleteParams
import com.scalar.models.accessGroups.AccessGroupRetrieveParams
import com.scalar.models.accessGroups.AccessGroupRetrieveResponse
import com.scalar.models.accessGroups.AccessGroupUpdateParams
import com.scalar.services.blocking.accessGroups.DomainService
import java.util.function.Consumer

/** Access Groups */
interface AccessGroupService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): AccessGroupService

    /** Access Groups */
    fun domains(): DomainService

    /**
     * Create a group for the current team. Requires docs edit permission and the access groups
     * billing feature. Domains are exact email domains, without wildcards or implicit subdomain
     * matching.
     */
    fun create(): AccessGroupCreateResponse = create(AccessGroupCreateParams.none())

    /** @see create */
    fun create(
        params: AccessGroupCreateParams = AccessGroupCreateParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): AccessGroupCreateResponse

    /** @see create */
    fun create(params: AccessGroupCreateParams): AccessGroupCreateResponse =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(requestOptions: RequestOptions): AccessGroupCreateResponse =
        create(AccessGroupCreateParams.none(), requestOptions)

    /** Get a group and its email and domain allowlists by slug. */
    fun retrieve(slug: String): AccessGroupRetrieveResponse =
        retrieve(slug, AccessGroupRetrieveParams.none())

    /** @see retrieve */
    fun retrieve(
        slug: String,
        params: AccessGroupRetrieveParams = AccessGroupRetrieveParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): AccessGroupRetrieveResponse = retrieve(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see retrieve */
    fun retrieve(slug: String, params: AccessGroupRetrieveParams): AccessGroupRetrieveResponse =
        retrieve(slug, params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(
        params: AccessGroupRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): AccessGroupRetrieveResponse

    /** @see retrieve */
    fun retrieve(params: AccessGroupRetrieveParams): AccessGroupRetrieveResponse =
        retrieve(params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(slug: String, requestOptions: RequestOptions): AccessGroupRetrieveResponse =
        retrieve(slug, AccessGroupRetrieveParams.none(), requestOptions)

    /**
     * Update group metadata. Requires docs edit permission. After changing the slug, use the new
     * slug in subsequent requests.
     */
    fun update(pathSlug: String): Any? = update(pathSlug, AccessGroupUpdateParams.none())

    /** @see update */
    fun update(
        pathSlug: String,
        params: AccessGroupUpdateParams = AccessGroupUpdateParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = update(params.toBuilder().pathSlug(pathSlug).build(), requestOptions)

    /** @see update */
    fun update(pathSlug: String, params: AccessGroupUpdateParams): Any? =
        update(pathSlug, params, RequestOptions.none())

    /** @see update */
    fun update(
        params: AccessGroupUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see update */
    fun update(params: AccessGroupUpdateParams): Any? = update(params, RequestOptions.none())

    /** @see update */
    fun update(pathSlug: String, requestOptions: RequestOptions): Any? =
        update(pathSlug, AccessGroupUpdateParams.none(), requestOptions)

    /** Delete a group and remove its project assignments. Requires docs edit permission. */
    fun delete(slug: String): Any? = delete(slug, AccessGroupDeleteParams.none())

    /** @see delete */
    fun delete(
        slug: String,
        params: AccessGroupDeleteParams = AccessGroupDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = delete(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see delete */
    fun delete(slug: String, params: AccessGroupDeleteParams): Any? =
        delete(slug, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: AccessGroupDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see delete */
    fun delete(params: AccessGroupDeleteParams): Any? = delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(slug: String, requestOptions: RequestOptions): Any? =
        delete(slug, AccessGroupDeleteParams.none(), requestOptions)

    /**
     * A view of [AccessGroupService] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): AccessGroupService.WithRawResponse

        /** Access Groups */
        fun domains(): DomainService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/access-groups`, but is otherwise the same as
         * [AccessGroupService.create].
         */
        @MustBeClosed
        fun create(): HttpResponseFor<AccessGroupCreateResponse> =
            create(AccessGroupCreateParams.none())

        /** @see create */
        @MustBeClosed
        fun create(
            params: AccessGroupCreateParams = AccessGroupCreateParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<AccessGroupCreateResponse>

        /** @see create */
        @MustBeClosed
        fun create(params: AccessGroupCreateParams): HttpResponseFor<AccessGroupCreateResponse> =
            create(params, RequestOptions.none())

        /** @see create */
        @MustBeClosed
        fun create(requestOptions: RequestOptions): HttpResponseFor<AccessGroupCreateResponse> =
            create(AccessGroupCreateParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/access-groups/{slug}`, but is otherwise the same
         * as [AccessGroupService.retrieve].
         */
        @MustBeClosed
        fun retrieve(slug: String): HttpResponseFor<AccessGroupRetrieveResponse> =
            retrieve(slug, AccessGroupRetrieveParams.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            slug: String,
            params: AccessGroupRetrieveParams = AccessGroupRetrieveParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<AccessGroupRetrieveResponse> =
            retrieve(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            slug: String,
            params: AccessGroupRetrieveParams,
        ): HttpResponseFor<AccessGroupRetrieveResponse> =
            retrieve(slug, params, RequestOptions.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            params: AccessGroupRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<AccessGroupRetrieveResponse>

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            params: AccessGroupRetrieveParams
        ): HttpResponseFor<AccessGroupRetrieveResponse> = retrieve(params, RequestOptions.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            slug: String,
            requestOptions: RequestOptions,
        ): HttpResponseFor<AccessGroupRetrieveResponse> =
            retrieve(slug, AccessGroupRetrieveParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `patch /v1/access-groups/{slug}`, but is otherwise the
         * same as [AccessGroupService.update].
         */
        @MustBeClosed
        fun update(pathSlug: String): HttpResponseFor<Any?> =
            update(pathSlug, AccessGroupUpdateParams.none())

        /** @see update */
        @MustBeClosed
        fun update(
            pathSlug: String,
            params: AccessGroupUpdateParams = AccessGroupUpdateParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            update(params.toBuilder().pathSlug(pathSlug).build(), requestOptions)

        /** @see update */
        @MustBeClosed
        fun update(pathSlug: String, params: AccessGroupUpdateParams): HttpResponseFor<Any?> =
            update(pathSlug, params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            params: AccessGroupUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see update */
        @MustBeClosed
        fun update(params: AccessGroupUpdateParams): HttpResponseFor<Any?> =
            update(params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(pathSlug: String, requestOptions: RequestOptions): HttpResponseFor<Any?> =
            update(pathSlug, AccessGroupUpdateParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/access-groups/{slug}`, but is otherwise the
         * same as [AccessGroupService.delete].
         */
        @MustBeClosed
        fun delete(slug: String): HttpResponseFor<Any?> =
            delete(slug, AccessGroupDeleteParams.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            slug: String,
            params: AccessGroupDeleteParams = AccessGroupDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> = delete(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see delete */
        @MustBeClosed
        fun delete(slug: String, params: AccessGroupDeleteParams): HttpResponseFor<Any?> =
            delete(slug, params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            params: AccessGroupDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see delete */
        @MustBeClosed
        fun delete(params: AccessGroupDeleteParams): HttpResponseFor<Any?> =
            delete(params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(slug: String, requestOptions: RequestOptions): HttpResponseFor<Any?> =
            delete(slug, AccessGroupDeleteParams.none(), requestOptions)
    }
}
