// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.handlers.errorBodyHandler
import com.scalar.core.handlers.errorHandler
import com.scalar.core.handlers.jsonHandler
import com.scalar.core.http.HttpMethod
import com.scalar.core.http.HttpRequest
import com.scalar.core.http.HttpResponse
import com.scalar.core.http.HttpResponse.Handler
import com.scalar.core.http.HttpResponseFor
import com.scalar.core.http.json
import com.scalar.core.http.parseable
import com.scalar.core.prepare
import com.scalar.models.authentication.AuthenticationExchangePersonalTokenParams
import com.scalar.models.authentication.AuthenticationExchangePersonalTokenResponse
import com.scalar.models.authentication.AuthenticationListCurrentUserParams
import com.scalar.models.authentication.AuthenticationListCurrentUserResponse
import java.util.function.Consumer

/** Authentication */
class AuthenticationServiceImpl internal constructor(private val clientOptions: ClientOptions) :
    AuthenticationService {

    private val withRawResponse: AuthenticationService.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): AuthenticationService.WithRawResponse = withRawResponse

    override fun withOptions(modifier: Consumer<ClientOptions.Builder>): AuthenticationService =
        AuthenticationServiceImpl(clientOptions.toBuilder().apply(modifier::accept).build())

    override fun exchangePersonalToken(
        params: AuthenticationExchangePersonalTokenParams,
        requestOptions: RequestOptions,
    ): AuthenticationExchangePersonalTokenResponse =
        // post /v1/auth/exchange
        withRawResponse().exchangePersonalToken(params, requestOptions).parse()

    override fun listCurrentUser(
        params: AuthenticationListCurrentUserParams,
        requestOptions: RequestOptions,
    ): AuthenticationListCurrentUserResponse =
        // get /v1/auth/me
        withRawResponse().listCurrentUser(params, requestOptions).parse()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        AuthenticationService.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): AuthenticationService.WithRawResponse =
            AuthenticationServiceImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier::accept).build()
            )

        private val exchangePersonalTokenHandler:
            Handler<AuthenticationExchangePersonalTokenResponse> =
            jsonHandler<AuthenticationExchangePersonalTokenResponse>(clientOptions.jsonMapper)

        override fun exchangePersonalToken(
            params: AuthenticationExchangePersonalTokenParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<AuthenticationExchangePersonalTokenResponse> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "auth", "exchange")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { exchangePersonalTokenHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val listCurrentUserHandler: Handler<AuthenticationListCurrentUserResponse> =
            jsonHandler<AuthenticationListCurrentUserResponse>(clientOptions.jsonMapper)

        override fun listCurrentUser(
            params: AuthenticationListCurrentUserParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<AuthenticationListCurrentUserResponse> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "auth", "me")
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { listCurrentUserHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }
    }
}
