// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.google.errorprone.annotations.MustBeClosed
import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.ManagedDocVersion
import com.scalar.models.registry.RegistryCreateApiDocumentAccessGroupParams
import com.scalar.models.registry.RegistryCreateApiDocumentParams
import com.scalar.models.registry.RegistryCreateApiDocumentResponse
import com.scalar.models.registry.RegistryCreateApiDocumentVersionParams
import com.scalar.models.registry.RegistryDeleteApiDocumentAccessGroupParams
import com.scalar.models.registry.RegistryDeleteApiDocumentParams
import com.scalar.models.registry.RegistryDeleteApiDocumentVersionParams
import com.scalar.models.registry.RegistryListAllApiDocumentsParams
import com.scalar.models.registry.RegistryListAllApiDocumentsResponse
import com.scalar.models.registry.RegistryListApiDocumentVersionMetadataParams
import com.scalar.models.registry.RegistryListApiDocumentsParams
import com.scalar.models.registry.RegistryListApiDocumentsResponse
import com.scalar.models.registry.RegistryRetrieveApiDocumentVersionParams
import com.scalar.models.registry.RegistryUpdateApiDocumentParams
import com.scalar.models.registry.RegistryUpdateApiDocumentVersionParams
import com.scalar.models.registry.RegistryUpdateApiDocumentVersionResponse
import java.util.function.Consumer

/** Registry */
interface RegistryService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): RegistryService

    /** Create an API document. */
    fun createApiDocument(
        namespace: String,
        params: RegistryCreateApiDocumentParams,
    ): RegistryCreateApiDocumentResponse =
        createApiDocument(namespace, params, RequestOptions.none())

    /** @see createApiDocument */
    fun createApiDocument(
        namespace: String,
        params: RegistryCreateApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): RegistryCreateApiDocumentResponse =
        createApiDocument(params.toBuilder().namespace(namespace).build(), requestOptions)

    /** @see createApiDocument */
    fun createApiDocument(
        params: RegistryCreateApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): RegistryCreateApiDocumentResponse

    /** @see createApiDocument */
    fun createApiDocument(
        params: RegistryCreateApiDocumentParams
    ): RegistryCreateApiDocumentResponse = createApiDocument(params, RequestOptions.none())

    /** Add an access group to an API document. */
    fun createApiDocumentAccessGroup(
        slug: String,
        params: RegistryCreateApiDocumentAccessGroupParams,
    ): Any? = createApiDocumentAccessGroup(slug, params, RequestOptions.none())

    /** @see createApiDocumentAccessGroup */
    fun createApiDocumentAccessGroup(
        slug: String,
        params: RegistryCreateApiDocumentAccessGroupParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = createApiDocumentAccessGroup(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see createApiDocumentAccessGroup */
    fun createApiDocumentAccessGroup(
        params: RegistryCreateApiDocumentAccessGroupParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see createApiDocumentAccessGroup */
    fun createApiDocumentAccessGroup(params: RegistryCreateApiDocumentAccessGroupParams): Any? =
        createApiDocumentAccessGroup(params, RequestOptions.none())

    /** Create a new API document version. */
    fun createApiDocumentVersion(
        slug: String,
        params: RegistryCreateApiDocumentVersionParams,
    ): ManagedDocVersion = createApiDocumentVersion(slug, params, RequestOptions.none())

    /** @see createApiDocumentVersion */
    fun createApiDocumentVersion(
        slug: String,
        params: RegistryCreateApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): ManagedDocVersion =
        createApiDocumentVersion(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see createApiDocumentVersion */
    fun createApiDocumentVersion(
        params: RegistryCreateApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): ManagedDocVersion

    /** @see createApiDocumentVersion */
    fun createApiDocumentVersion(
        params: RegistryCreateApiDocumentVersionParams
    ): ManagedDocVersion = createApiDocumentVersion(params, RequestOptions.none())

    /** Delete an API document and all versions. */
    fun deleteApiDocument(slug: String, params: RegistryDeleteApiDocumentParams): Any? =
        deleteApiDocument(slug, params, RequestOptions.none())

    /** @see deleteApiDocument */
    fun deleteApiDocument(
        slug: String,
        params: RegistryDeleteApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = deleteApiDocument(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see deleteApiDocument */
    fun deleteApiDocument(
        params: RegistryDeleteApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see deleteApiDocument */
    fun deleteApiDocument(params: RegistryDeleteApiDocumentParams): Any? =
        deleteApiDocument(params, RequestOptions.none())

    /** Remove an access group from an API document. */
    fun deleteApiDocumentAccessGroup(
        slug: String,
        params: RegistryDeleteApiDocumentAccessGroupParams,
    ): Any? = deleteApiDocumentAccessGroup(slug, params, RequestOptions.none())

    /** @see deleteApiDocumentAccessGroup */
    fun deleteApiDocumentAccessGroup(
        slug: String,
        params: RegistryDeleteApiDocumentAccessGroupParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = deleteApiDocumentAccessGroup(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see deleteApiDocumentAccessGroup */
    fun deleteApiDocumentAccessGroup(
        params: RegistryDeleteApiDocumentAccessGroupParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see deleteApiDocumentAccessGroup */
    fun deleteApiDocumentAccessGroup(params: RegistryDeleteApiDocumentAccessGroupParams): Any? =
        deleteApiDocumentAccessGroup(params, RequestOptions.none())

    /** Delete a specific API document version. */
    fun deleteApiDocumentVersion(
        semver: String,
        params: RegistryDeleteApiDocumentVersionParams,
    ): Any? = deleteApiDocumentVersion(semver, params, RequestOptions.none())

    /** @see deleteApiDocumentVersion */
    fun deleteApiDocumentVersion(
        semver: String,
        params: RegistryDeleteApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = deleteApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see deleteApiDocumentVersion */
    fun deleteApiDocumentVersion(
        params: RegistryDeleteApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see deleteApiDocumentVersion */
    fun deleteApiDocumentVersion(params: RegistryDeleteApiDocumentVersionParams): Any? =
        deleteApiDocumentVersion(params, RequestOptions.none())

    /** List all API documents across every namespace the caller can access. */
    fun listAllApiDocuments(): List<RegistryListAllApiDocumentsResponse> =
        listAllApiDocuments(RegistryListAllApiDocumentsParams.none())

    /** @see listAllApiDocuments */
    fun listAllApiDocuments(
        params: RegistryListAllApiDocumentsParams = RegistryListAllApiDocumentsParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<RegistryListAllApiDocumentsResponse>

    /** @see listAllApiDocuments */
    fun listAllApiDocuments(
        params: RegistryListAllApiDocumentsParams
    ): List<RegistryListAllApiDocumentsResponse> =
        listAllApiDocuments(params, RequestOptions.none())

    /** @see listAllApiDocuments */
    fun listAllApiDocuments(
        requestOptions: RequestOptions
    ): List<RegistryListAllApiDocumentsResponse> =
        listAllApiDocuments(RegistryListAllApiDocumentsParams.none(), requestOptions)

    /** Get metadata (uid, content shas, version sha, tags) for a specific API document version. */
    fun listApiDocumentVersionMetadata(
        semver: String,
        params: RegistryListApiDocumentVersionMetadataParams,
    ): ManagedDocVersion = listApiDocumentVersionMetadata(semver, params, RequestOptions.none())

    /** @see listApiDocumentVersionMetadata */
    fun listApiDocumentVersionMetadata(
        semver: String,
        params: RegistryListApiDocumentVersionMetadataParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): ManagedDocVersion =
        listApiDocumentVersionMetadata(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see listApiDocumentVersionMetadata */
    fun listApiDocumentVersionMetadata(
        params: RegistryListApiDocumentVersionMetadataParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): ManagedDocVersion

    /** @see listApiDocumentVersionMetadata */
    fun listApiDocumentVersionMetadata(
        params: RegistryListApiDocumentVersionMetadataParams
    ): ManagedDocVersion = listApiDocumentVersionMetadata(params, RequestOptions.none())

    /** List API documents in a namespace. */
    fun listApiDocuments(namespace: String): List<RegistryListApiDocumentsResponse> =
        listApiDocuments(namespace, RegistryListApiDocumentsParams.none())

    /** @see listApiDocuments */
    fun listApiDocuments(
        namespace: String,
        params: RegistryListApiDocumentsParams = RegistryListApiDocumentsParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<RegistryListApiDocumentsResponse> =
        listApiDocuments(params.toBuilder().namespace(namespace).build(), requestOptions)

    /** @see listApiDocuments */
    fun listApiDocuments(
        namespace: String,
        params: RegistryListApiDocumentsParams,
    ): List<RegistryListApiDocumentsResponse> =
        listApiDocuments(namespace, params, RequestOptions.none())

    /** @see listApiDocuments */
    fun listApiDocuments(
        params: RegistryListApiDocumentsParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<RegistryListApiDocumentsResponse>

    /** @see listApiDocuments */
    fun listApiDocuments(
        params: RegistryListApiDocumentsParams
    ): List<RegistryListApiDocumentsResponse> = listApiDocuments(params, RequestOptions.none())

    /** @see listApiDocuments */
    fun listApiDocuments(
        namespace: String,
        requestOptions: RequestOptions,
    ): List<RegistryListApiDocumentsResponse> =
        listApiDocuments(namespace, RegistryListApiDocumentsParams.none(), requestOptions)

    /** Get a specific API document version. */
    fun retrieveApiDocumentVersion(
        semver: String,
        params: RegistryRetrieveApiDocumentVersionParams,
    ): String = retrieveApiDocumentVersion(semver, params, RequestOptions.none())

    /** @see retrieveApiDocumentVersion */
    fun retrieveApiDocumentVersion(
        semver: String,
        params: RegistryRetrieveApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): String =
        retrieveApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see retrieveApiDocumentVersion */
    fun retrieveApiDocumentVersion(
        params: RegistryRetrieveApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): String

    /** @see retrieveApiDocumentVersion */
    fun retrieveApiDocumentVersion(params: RegistryRetrieveApiDocumentVersionParams): String =
        retrieveApiDocumentVersion(params, RequestOptions.none())

    /** Update metadata for an API document. */
    fun updateApiDocument(slug: String, params: RegistryUpdateApiDocumentParams): Any? =
        updateApiDocument(slug, params, RequestOptions.none())

    /** @see updateApiDocument */
    fun updateApiDocument(
        slug: String,
        params: RegistryUpdateApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = updateApiDocument(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see updateApiDocument */
    fun updateApiDocument(
        params: RegistryUpdateApiDocumentParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see updateApiDocument */
    fun updateApiDocument(params: RegistryUpdateApiDocumentParams): Any? =
        updateApiDocument(params, RequestOptions.none())

    /** Update the registry file content for an API document version. */
    fun updateApiDocumentVersion(
        semver: String,
        params: RegistryUpdateApiDocumentVersionParams,
    ): RegistryUpdateApiDocumentVersionResponse =
        updateApiDocumentVersion(semver, params, RequestOptions.none())

    /** @see updateApiDocumentVersion */
    fun updateApiDocumentVersion(
        semver: String,
        params: RegistryUpdateApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): RegistryUpdateApiDocumentVersionResponse =
        updateApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see updateApiDocumentVersion */
    fun updateApiDocumentVersion(
        params: RegistryUpdateApiDocumentVersionParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): RegistryUpdateApiDocumentVersionResponse

    /** @see updateApiDocumentVersion */
    fun updateApiDocumentVersion(
        params: RegistryUpdateApiDocumentVersionParams
    ): RegistryUpdateApiDocumentVersionResponse =
        updateApiDocumentVersion(params, RequestOptions.none())

    /** A view of [RegistryService] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(modifier: Consumer<ClientOptions.Builder>): RegistryService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/apis/{namespace}`, but is otherwise the same as
         * [RegistryService.createApiDocument].
         */
        @MustBeClosed
        fun createApiDocument(
            namespace: String,
            params: RegistryCreateApiDocumentParams,
        ): HttpResponseFor<RegistryCreateApiDocumentResponse> =
            createApiDocument(namespace, params, RequestOptions.none())

        /** @see createApiDocument */
        @MustBeClosed
        fun createApiDocument(
            namespace: String,
            params: RegistryCreateApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<RegistryCreateApiDocumentResponse> =
            createApiDocument(params.toBuilder().namespace(namespace).build(), requestOptions)

        /** @see createApiDocument */
        @MustBeClosed
        fun createApiDocument(
            params: RegistryCreateApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<RegistryCreateApiDocumentResponse>

        /** @see createApiDocument */
        @MustBeClosed
        fun createApiDocument(
            params: RegistryCreateApiDocumentParams
        ): HttpResponseFor<RegistryCreateApiDocumentResponse> =
            createApiDocument(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `post /v1/apis/{namespace}/{slug}/access-group`, but is
         * otherwise the same as [RegistryService.createApiDocumentAccessGroup].
         */
        @MustBeClosed
        fun createApiDocumentAccessGroup(
            slug: String,
            params: RegistryCreateApiDocumentAccessGroupParams,
        ): HttpResponseFor<Any?> = createApiDocumentAccessGroup(slug, params, RequestOptions.none())

        /** @see createApiDocumentAccessGroup */
        @MustBeClosed
        fun createApiDocumentAccessGroup(
            slug: String,
            params: RegistryCreateApiDocumentAccessGroupParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            createApiDocumentAccessGroup(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see createApiDocumentAccessGroup */
        @MustBeClosed
        fun createApiDocumentAccessGroup(
            params: RegistryCreateApiDocumentAccessGroupParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see createApiDocumentAccessGroup */
        @MustBeClosed
        fun createApiDocumentAccessGroup(
            params: RegistryCreateApiDocumentAccessGroupParams
        ): HttpResponseFor<Any?> = createApiDocumentAccessGroup(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `post /v1/apis/{namespace}/{slug}/version`, but is
         * otherwise the same as [RegistryService.createApiDocumentVersion].
         */
        @MustBeClosed
        fun createApiDocumentVersion(
            slug: String,
            params: RegistryCreateApiDocumentVersionParams,
        ): HttpResponseFor<ManagedDocVersion> =
            createApiDocumentVersion(slug, params, RequestOptions.none())

        /** @see createApiDocumentVersion */
        @MustBeClosed
        fun createApiDocumentVersion(
            slug: String,
            params: RegistryCreateApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<ManagedDocVersion> =
            createApiDocumentVersion(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see createApiDocumentVersion */
        @MustBeClosed
        fun createApiDocumentVersion(
            params: RegistryCreateApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<ManagedDocVersion>

        /** @see createApiDocumentVersion */
        @MustBeClosed
        fun createApiDocumentVersion(
            params: RegistryCreateApiDocumentVersionParams
        ): HttpResponseFor<ManagedDocVersion> =
            createApiDocumentVersion(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `delete /v1/apis/{namespace}/{slug}`, but is otherwise
         * the same as [RegistryService.deleteApiDocument].
         */
        @MustBeClosed
        fun deleteApiDocument(
            slug: String,
            params: RegistryDeleteApiDocumentParams,
        ): HttpResponseFor<Any?> = deleteApiDocument(slug, params, RequestOptions.none())

        /** @see deleteApiDocument */
        @MustBeClosed
        fun deleteApiDocument(
            slug: String,
            params: RegistryDeleteApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            deleteApiDocument(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see deleteApiDocument */
        @MustBeClosed
        fun deleteApiDocument(
            params: RegistryDeleteApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see deleteApiDocument */
        @MustBeClosed
        fun deleteApiDocument(params: RegistryDeleteApiDocumentParams): HttpResponseFor<Any?> =
            deleteApiDocument(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `delete /v1/apis/{namespace}/{slug}/access-group`, but is
         * otherwise the same as [RegistryService.deleteApiDocumentAccessGroup].
         */
        @MustBeClosed
        fun deleteApiDocumentAccessGroup(
            slug: String,
            params: RegistryDeleteApiDocumentAccessGroupParams,
        ): HttpResponseFor<Any?> = deleteApiDocumentAccessGroup(slug, params, RequestOptions.none())

        /** @see deleteApiDocumentAccessGroup */
        @MustBeClosed
        fun deleteApiDocumentAccessGroup(
            slug: String,
            params: RegistryDeleteApiDocumentAccessGroupParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            deleteApiDocumentAccessGroup(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see deleteApiDocumentAccessGroup */
        @MustBeClosed
        fun deleteApiDocumentAccessGroup(
            params: RegistryDeleteApiDocumentAccessGroupParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see deleteApiDocumentAccessGroup */
        @MustBeClosed
        fun deleteApiDocumentAccessGroup(
            params: RegistryDeleteApiDocumentAccessGroupParams
        ): HttpResponseFor<Any?> = deleteApiDocumentAccessGroup(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `delete /v1/apis/{namespace}/{slug}/version/{semver}`,
         * but is otherwise the same as [RegistryService.deleteApiDocumentVersion].
         */
        @MustBeClosed
        fun deleteApiDocumentVersion(
            semver: String,
            params: RegistryDeleteApiDocumentVersionParams,
        ): HttpResponseFor<Any?> = deleteApiDocumentVersion(semver, params, RequestOptions.none())

        /** @see deleteApiDocumentVersion */
        @MustBeClosed
        fun deleteApiDocumentVersion(
            semver: String,
            params: RegistryDeleteApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            deleteApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

        /** @see deleteApiDocumentVersion */
        @MustBeClosed
        fun deleteApiDocumentVersion(
            params: RegistryDeleteApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see deleteApiDocumentVersion */
        @MustBeClosed
        fun deleteApiDocumentVersion(
            params: RegistryDeleteApiDocumentVersionParams
        ): HttpResponseFor<Any?> = deleteApiDocumentVersion(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `get /v1/apis`, but is otherwise the same as
         * [RegistryService.listAllApiDocuments].
         */
        @MustBeClosed
        fun listAllApiDocuments(): HttpResponseFor<List<RegistryListAllApiDocumentsResponse>> =
            listAllApiDocuments(RegistryListAllApiDocumentsParams.none())

        /** @see listAllApiDocuments */
        @MustBeClosed
        fun listAllApiDocuments(
            params: RegistryListAllApiDocumentsParams = RegistryListAllApiDocumentsParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<RegistryListAllApiDocumentsResponse>>

        /** @see listAllApiDocuments */
        @MustBeClosed
        fun listAllApiDocuments(
            params: RegistryListAllApiDocumentsParams
        ): HttpResponseFor<List<RegistryListAllApiDocumentsResponse>> =
            listAllApiDocuments(params, RequestOptions.none())

        /** @see listAllApiDocuments */
        @MustBeClosed
        fun listAllApiDocuments(
            requestOptions: RequestOptions
        ): HttpResponseFor<List<RegistryListAllApiDocumentsResponse>> =
            listAllApiDocuments(RegistryListAllApiDocumentsParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get
         * /v1/apis/{namespace}/{slug}/version/{semver}/metadata`, but is otherwise the same as
         * [RegistryService.listApiDocumentVersionMetadata].
         */
        @MustBeClosed
        fun listApiDocumentVersionMetadata(
            semver: String,
            params: RegistryListApiDocumentVersionMetadataParams,
        ): HttpResponseFor<ManagedDocVersion> =
            listApiDocumentVersionMetadata(semver, params, RequestOptions.none())

        /** @see listApiDocumentVersionMetadata */
        @MustBeClosed
        fun listApiDocumentVersionMetadata(
            semver: String,
            params: RegistryListApiDocumentVersionMetadataParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<ManagedDocVersion> =
            listApiDocumentVersionMetadata(
                params.toBuilder().semver(semver).build(),
                requestOptions,
            )

        /** @see listApiDocumentVersionMetadata */
        @MustBeClosed
        fun listApiDocumentVersionMetadata(
            params: RegistryListApiDocumentVersionMetadataParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<ManagedDocVersion>

        /** @see listApiDocumentVersionMetadata */
        @MustBeClosed
        fun listApiDocumentVersionMetadata(
            params: RegistryListApiDocumentVersionMetadataParams
        ): HttpResponseFor<ManagedDocVersion> =
            listApiDocumentVersionMetadata(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `get /v1/apis/{namespace}`, but is otherwise the same as
         * [RegistryService.listApiDocuments].
         */
        @MustBeClosed
        fun listApiDocuments(
            namespace: String
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>> =
            listApiDocuments(namespace, RegistryListApiDocumentsParams.none())

        /** @see listApiDocuments */
        @MustBeClosed
        fun listApiDocuments(
            namespace: String,
            params: RegistryListApiDocumentsParams = RegistryListApiDocumentsParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>> =
            listApiDocuments(params.toBuilder().namespace(namespace).build(), requestOptions)

        /** @see listApiDocuments */
        @MustBeClosed
        fun listApiDocuments(
            namespace: String,
            params: RegistryListApiDocumentsParams,
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>> =
            listApiDocuments(namespace, params, RequestOptions.none())

        /** @see listApiDocuments */
        @MustBeClosed
        fun listApiDocuments(
            params: RegistryListApiDocumentsParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>>

        /** @see listApiDocuments */
        @MustBeClosed
        fun listApiDocuments(
            params: RegistryListApiDocumentsParams
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>> =
            listApiDocuments(params, RequestOptions.none())

        /** @see listApiDocuments */
        @MustBeClosed
        fun listApiDocuments(
            namespace: String,
            requestOptions: RequestOptions,
        ): HttpResponseFor<List<RegistryListApiDocumentsResponse>> =
            listApiDocuments(namespace, RegistryListApiDocumentsParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/apis/{namespace}/{slug}/version/{semver}`, but
         * is otherwise the same as [RegistryService.retrieveApiDocumentVersion].
         */
        @MustBeClosed
        fun retrieveApiDocumentVersion(
            semver: String,
            params: RegistryRetrieveApiDocumentVersionParams,
        ): HttpResponseFor<String> =
            retrieveApiDocumentVersion(semver, params, RequestOptions.none())

        /** @see retrieveApiDocumentVersion */
        @MustBeClosed
        fun retrieveApiDocumentVersion(
            semver: String,
            params: RegistryRetrieveApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<String> =
            retrieveApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

        /** @see retrieveApiDocumentVersion */
        @MustBeClosed
        fun retrieveApiDocumentVersion(
            params: RegistryRetrieveApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<String>

        /** @see retrieveApiDocumentVersion */
        @MustBeClosed
        fun retrieveApiDocumentVersion(
            params: RegistryRetrieveApiDocumentVersionParams
        ): HttpResponseFor<String> = retrieveApiDocumentVersion(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `patch /v1/apis/{namespace}/{slug}`, but is otherwise the
         * same as [RegistryService.updateApiDocument].
         */
        @MustBeClosed
        fun updateApiDocument(
            slug: String,
            params: RegistryUpdateApiDocumentParams,
        ): HttpResponseFor<Any?> = updateApiDocument(slug, params, RequestOptions.none())

        /** @see updateApiDocument */
        @MustBeClosed
        fun updateApiDocument(
            slug: String,
            params: RegistryUpdateApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> =
            updateApiDocument(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see updateApiDocument */
        @MustBeClosed
        fun updateApiDocument(
            params: RegistryUpdateApiDocumentParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see updateApiDocument */
        @MustBeClosed
        fun updateApiDocument(params: RegistryUpdateApiDocumentParams): HttpResponseFor<Any?> =
            updateApiDocument(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `patch /v1/apis/{namespace}/{slug}/version/{semver}`, but
         * is otherwise the same as [RegistryService.updateApiDocumentVersion].
         */
        @MustBeClosed
        fun updateApiDocumentVersion(
            semver: String,
            params: RegistryUpdateApiDocumentVersionParams,
        ): HttpResponseFor<RegistryUpdateApiDocumentVersionResponse> =
            updateApiDocumentVersion(semver, params, RequestOptions.none())

        /** @see updateApiDocumentVersion */
        @MustBeClosed
        fun updateApiDocumentVersion(
            semver: String,
            params: RegistryUpdateApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<RegistryUpdateApiDocumentVersionResponse> =
            updateApiDocumentVersion(params.toBuilder().semver(semver).build(), requestOptions)

        /** @see updateApiDocumentVersion */
        @MustBeClosed
        fun updateApiDocumentVersion(
            params: RegistryUpdateApiDocumentVersionParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<RegistryUpdateApiDocumentVersionResponse>

        /** @see updateApiDocumentVersion */
        @MustBeClosed
        fun updateApiDocumentVersion(
            params: RegistryUpdateApiDocumentVersionParams
        ): HttpResponseFor<RegistryUpdateApiDocumentVersionResponse> =
            updateApiDocumentVersion(params, RequestOptions.none())
    }
}
