// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.checkRequired
import com.scalar.core.handlers.errorBodyHandler
import com.scalar.core.handlers.errorHandler
import com.scalar.core.handlers.jsonHandler
import com.scalar.core.handlers.stringHandler
import com.scalar.core.http.HttpMethod
import com.scalar.core.http.HttpRequest
import com.scalar.core.http.HttpResponse
import com.scalar.core.http.HttpResponse.Handler
import com.scalar.core.http.HttpResponseFor
import com.scalar.core.http.json
import com.scalar.core.http.parseable
import com.scalar.core.prepare
import com.scalar.models.Uid
import com.scalar.models.rules.RuleCreateRulesetAccessGroupParams
import com.scalar.models.rules.RuleCreateRulesetParams
import com.scalar.models.rules.RuleDeleteRulesetAccessGroupParams
import com.scalar.models.rules.RuleDeleteRulesetParams
import com.scalar.models.rules.RuleListRulesetsParams
import com.scalar.models.rules.RuleListRulesetsResponse
import com.scalar.models.rules.RuleRetrieveRulesetDocumentParams
import com.scalar.models.rules.RuleUpdateRulesetParams
import java.util.function.Consumer
import kotlin.jvm.optionals.getOrNull

/** Rules */
class RuleServiceImpl internal constructor(private val clientOptions: ClientOptions) : RuleService {

    private val withRawResponse: RuleService.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): RuleService.WithRawResponse = withRawResponse

    override fun withOptions(modifier: Consumer<ClientOptions.Builder>): RuleService =
        RuleServiceImpl(clientOptions.toBuilder().apply(modifier::accept).build())

    override fun createRuleset(
        params: RuleCreateRulesetParams,
        requestOptions: RequestOptions,
    ): Uid =
        // post /v1/rulesets/{namespace}
        withRawResponse().createRuleset(params, requestOptions).parse()

    override fun createRulesetAccessGroup(
        params: RuleCreateRulesetAccessGroupParams,
        requestOptions: RequestOptions,
    ): Any? =
        // post /v1/rulesets/{namespace}/{slug}/access-group
        withRawResponse().createRulesetAccessGroup(params, requestOptions).parse()

    override fun deleteRuleset(
        params: RuleDeleteRulesetParams,
        requestOptions: RequestOptions,
    ): Any? =
        // delete /v1/rulesets/{namespace}/{slug}
        withRawResponse().deleteRuleset(params, requestOptions).parse()

    override fun deleteRulesetAccessGroup(
        params: RuleDeleteRulesetAccessGroupParams,
        requestOptions: RequestOptions,
    ): Any? =
        // delete /v1/rulesets/{namespace}/{slug}/access-group
        withRawResponse().deleteRulesetAccessGroup(params, requestOptions).parse()

    override fun listRulesets(
        params: RuleListRulesetsParams,
        requestOptions: RequestOptions,
    ): List<RuleListRulesetsResponse> =
        // get /v1/rulesets/{namespace}
        withRawResponse().listRulesets(params, requestOptions).parse()

    override fun retrieveRulesetDocument(
        params: RuleRetrieveRulesetDocumentParams,
        requestOptions: RequestOptions,
    ): String =
        // get /v1/rulesets/{namespace}/{slug}
        withRawResponse().retrieveRulesetDocument(params, requestOptions).parse()

    override fun updateRuleset(
        params: RuleUpdateRulesetParams,
        requestOptions: RequestOptions,
    ): Any? =
        // patch /v1/rulesets/{namespace}/{slug}
        withRawResponse().updateRuleset(params, requestOptions).parse()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        RuleService.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): RuleService.WithRawResponse =
            RuleServiceImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier::accept).build()
            )

        private val createRulesetHandler: Handler<Uid> = jsonHandler<Uid>(clientOptions.jsonMapper)

        override fun createRuleset(
            params: RuleCreateRulesetParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Uid> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("namespace", params.namespace().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "rulesets", params._pathParam(0))
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { createRulesetHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val createRulesetAccessGroupHandler: Handler<Any?> =
            jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun createRulesetAccessGroup(
            params: RuleCreateRulesetAccessGroupParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Any?> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments(
                        "v1",
                        "rulesets",
                        params._pathParam(0),
                        params._pathParam(1),
                        "access-group",
                    )
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { createRulesetAccessGroupHandler.handle(it) }
            }
        }

        private val deleteRulesetHandler: Handler<Any?> =
            jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun deleteRuleset(
            params: RuleDeleteRulesetParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Any?> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.DELETE)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "rulesets", params._pathParam(0), params._pathParam(1))
                    .apply { params._body().ifPresent { body(json(clientOptions.jsonMapper, it)) } }
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { deleteRulesetHandler.handle(it) }
            }
        }

        private val deleteRulesetAccessGroupHandler: Handler<Any?> =
            jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun deleteRulesetAccessGroup(
            params: RuleDeleteRulesetAccessGroupParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Any?> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.DELETE)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments(
                        "v1",
                        "rulesets",
                        params._pathParam(0),
                        params._pathParam(1),
                        "access-group",
                    )
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { deleteRulesetAccessGroupHandler.handle(it) }
            }
        }

        private val listRulesetsHandler: Handler<List<RuleListRulesetsResponse>> =
            jsonHandler<List<RuleListRulesetsResponse>>(clientOptions.jsonMapper)

        override fun listRulesets(
            params: RuleListRulesetsParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<List<RuleListRulesetsResponse>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("namespace", params.namespace().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "rulesets", params._pathParam(0))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { listRulesetsHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.forEach { it.validate() }
                        }
                    }
            }
        }

        private val retrieveRulesetDocumentHandler: Handler<String> = stringHandler()

        override fun retrieveRulesetDocument(
            params: RuleRetrieveRulesetDocumentParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<String> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "rulesets", params._pathParam(0), params._pathParam(1))
                    .putHeader("Accept", "text/plain")
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { retrieveRulesetDocumentHandler.handle(it) }
            }
        }

        private val updateRulesetHandler: Handler<Any?> =
            jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun updateRuleset(
            params: RuleUpdateRulesetParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Any?> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("pathSlug", params.pathSlug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.PATCH)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "rulesets", params._pathParam(0), params._pathParam(1))
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { updateRulesetHandler.handle(it) }
            }
        }
    }
}
