// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.google.errorprone.annotations.MustBeClosed
import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.Uid
import com.scalar.models.sdks.Sdk
import com.scalar.models.sdks.SdkBuildParams
import com.scalar.models.sdks.SdkBuildResponse
import com.scalar.models.sdks.SdkCreateParams
import com.scalar.models.sdks.SdkDeleteParams
import com.scalar.models.sdks.SdkListParams
import com.scalar.models.sdks.SdkListResponse
import com.scalar.models.sdks.SdkRetrieveParams
import com.scalar.models.sdks.SdkUpdateParams
import com.scalar.services.blocking.sdks.RepositoryService
import com.scalar.services.blocking.sdks.VersionService
import java.util.function.Consumer

/** SDKs */
interface SdkService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): SdkService

    /** SDKs */
    fun versions(): VersionService

    /** SDKs */
    fun repositories(): RepositoryService

    /** Create an SDK from an API document, targeting one or more languages. */
    fun create(params: SdkCreateParams): Uid = create(params, RequestOptions.none())

    /** @see create */
    fun create(params: SdkCreateParams, requestOptions: RequestOptions = RequestOptions.none()): Uid

    /** Get a single SDK by its uid. */
    fun retrieve(uid: String): Sdk = retrieve(uid, SdkRetrieveParams.none())

    /** @see retrieve */
    fun retrieve(
        uid: String,
        params: SdkRetrieveParams = SdkRetrieveParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Sdk = retrieve(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see retrieve */
    fun retrieve(uid: String, params: SdkRetrieveParams): Sdk =
        retrieve(uid, params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(
        params: SdkRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Sdk

    /** @see retrieve */
    fun retrieve(params: SdkRetrieveParams): Sdk = retrieve(params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(uid: String, requestOptions: RequestOptions): Sdk =
        retrieve(uid, SdkRetrieveParams.none(), requestOptions)

    /** Update SDK metadata, its linked API, or its config. */
    fun update(uid: String): Any? = update(uid, SdkUpdateParams.none())

    /** @see update */
    fun update(
        uid: String,
        params: SdkUpdateParams = SdkUpdateParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = update(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see update */
    fun update(uid: String, params: SdkUpdateParams): Any? =
        update(uid, params, RequestOptions.none())

    /** @see update */
    fun update(
        params: SdkUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see update */
    fun update(params: SdkUpdateParams): Any? = update(params, RequestOptions.none())

    /** @see update */
    fun update(uid: String, requestOptions: RequestOptions): Any? =
        update(uid, SdkUpdateParams.none(), requestOptions)

    /** List every SDK on the team. */
    fun list(): SdkListResponse = list(SdkListParams.none())

    /** @see list */
    fun list(
        params: SdkListParams = SdkListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): SdkListResponse

    /** @see list */
    fun list(params: SdkListParams): SdkListResponse = list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): SdkListResponse =
        list(SdkListParams.none(), requestOptions)

    /** Delete an SDK and every version it holds. */
    fun delete(uid: String): Any? = delete(uid, SdkDeleteParams.none())

    /** @see delete */
    fun delete(
        uid: String,
        params: SdkDeleteParams = SdkDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any? = delete(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see delete */
    fun delete(uid: String, params: SdkDeleteParams): Any? =
        delete(uid, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: SdkDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Any?

    /** @see delete */
    fun delete(params: SdkDeleteParams): Any? = delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(uid: String, requestOptions: RequestOptions): Any? =
        delete(uid, SdkDeleteParams.none(), requestOptions)

    /**
     * Start a build. Omit `version` to build the current work — the open draft, else the latest
     * version — and the resolved version comes back in the response.
     */
    fun build(uid: String): SdkBuildResponse = build(uid, SdkBuildParams.none())

    /** @see build */
    fun build(
        uid: String,
        params: SdkBuildParams = SdkBuildParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): SdkBuildResponse = build(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see build */
    fun build(uid: String, params: SdkBuildParams): SdkBuildResponse =
        build(uid, params, RequestOptions.none())

    /** @see build */
    fun build(
        params: SdkBuildParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): SdkBuildResponse

    /** @see build */
    fun build(params: SdkBuildParams): SdkBuildResponse = build(params, RequestOptions.none())

    /** @see build */
    fun build(uid: String, requestOptions: RequestOptions): SdkBuildResponse =
        build(uid, SdkBuildParams.none(), requestOptions)

    /** A view of [SdkService] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(modifier: Consumer<ClientOptions.Builder>): SdkService.WithRawResponse

        /** SDKs */
        fun versions(): VersionService.WithRawResponse

        /** SDKs */
        fun repositories(): RepositoryService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/sdks`, but is otherwise the same as
         * [SdkService.create].
         */
        @MustBeClosed
        fun create(params: SdkCreateParams): HttpResponseFor<Uid> =
            create(params, RequestOptions.none())

        /** @see create */
        @MustBeClosed
        fun create(
            params: SdkCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Uid>

        /**
         * Returns a raw HTTP response for `get /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkService.retrieve].
         */
        @MustBeClosed
        fun retrieve(uid: String): HttpResponseFor<Sdk> = retrieve(uid, SdkRetrieveParams.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            uid: String,
            params: SdkRetrieveParams = SdkRetrieveParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Sdk> = retrieve(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(uid: String, params: SdkRetrieveParams): HttpResponseFor<Sdk> =
            retrieve(uid, params, RequestOptions.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            params: SdkRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Sdk>

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(params: SdkRetrieveParams): HttpResponseFor<Sdk> =
            retrieve(params, RequestOptions.none())

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(uid: String, requestOptions: RequestOptions): HttpResponseFor<Sdk> =
            retrieve(uid, SdkRetrieveParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `patch /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkService.update].
         */
        @MustBeClosed
        fun update(uid: String): HttpResponseFor<Any?> = update(uid, SdkUpdateParams.none())

        /** @see update */
        @MustBeClosed
        fun update(
            uid: String,
            params: SdkUpdateParams = SdkUpdateParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> = update(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see update */
        @MustBeClosed
        fun update(uid: String, params: SdkUpdateParams): HttpResponseFor<Any?> =
            update(uid, params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            params: SdkUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see update */
        @MustBeClosed
        fun update(params: SdkUpdateParams): HttpResponseFor<Any?> =
            update(params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(uid: String, requestOptions: RequestOptions): HttpResponseFor<Any?> =
            update(uid, SdkUpdateParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/sdks`, but is otherwise the same as
         * [SdkService.list].
         */
        @MustBeClosed fun list(): HttpResponseFor<SdkListResponse> = list(SdkListParams.none())

        /** @see list */
        @MustBeClosed
        fun list(
            params: SdkListParams = SdkListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<SdkListResponse>

        /** @see list */
        @MustBeClosed
        fun list(params: SdkListParams): HttpResponseFor<SdkListResponse> =
            list(params, RequestOptions.none())

        /** @see list */
        @MustBeClosed
        fun list(requestOptions: RequestOptions): HttpResponseFor<SdkListResponse> =
            list(SdkListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkService.delete].
         */
        @MustBeClosed
        fun delete(uid: String): HttpResponseFor<Any?> = delete(uid, SdkDeleteParams.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            uid: String,
            params: SdkDeleteParams = SdkDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?> = delete(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see delete */
        @MustBeClosed
        fun delete(uid: String, params: SdkDeleteParams): HttpResponseFor<Any?> =
            delete(uid, params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            params: SdkDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Any?>

        /** @see delete */
        @MustBeClosed
        fun delete(params: SdkDeleteParams): HttpResponseFor<Any?> =
            delete(params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(uid: String, requestOptions: RequestOptions): HttpResponseFor<Any?> =
            delete(uid, SdkDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `post /v1/sdks/{uid}/build`, but is otherwise the same as
         * [SdkService.build].
         */
        @MustBeClosed
        fun build(uid: String): HttpResponseFor<SdkBuildResponse> =
            build(uid, SdkBuildParams.none())

        /** @see build */
        @MustBeClosed
        fun build(
            uid: String,
            params: SdkBuildParams = SdkBuildParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<SdkBuildResponse> =
            build(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see build */
        @MustBeClosed
        fun build(uid: String, params: SdkBuildParams): HttpResponseFor<SdkBuildResponse> =
            build(uid, params, RequestOptions.none())

        /** @see build */
        @MustBeClosed
        fun build(
            params: SdkBuildParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<SdkBuildResponse>

        /** @see build */
        @MustBeClosed
        fun build(params: SdkBuildParams): HttpResponseFor<SdkBuildResponse> =
            build(params, RequestOptions.none())

        /** @see build */
        @MustBeClosed
        fun build(uid: String, requestOptions: RequestOptions): HttpResponseFor<SdkBuildResponse> =
            build(uid, SdkBuildParams.none(), requestOptions)
    }
}
