// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.blocking

import com.google.errorprone.annotations.MustBeClosed
import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.teams.Team
import com.scalar.models.teams.TeamListParams
import com.scalar.services.blocking.teams.InviteService
import com.scalar.services.blocking.teams.MemberService
import java.util.function.Consumer

/** Teams */
interface TeamService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): TeamService

    /** Teams */
    fun members(): MemberService

    /** Teams */
    fun invites(): InviteService

    /** List all available teams */
    fun list(): List<Team> = list(TeamListParams.none())

    /** @see list */
    fun list(
        params: TeamListParams = TeamListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<Team>

    /** @see list */
    fun list(params: TeamListParams): List<Team> = list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): List<Team> =
        list(TeamListParams.none(), requestOptions)

    /** A view of [TeamService] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(modifier: Consumer<ClientOptions.Builder>): TeamService.WithRawResponse

        /** Teams */
        fun members(): MemberService.WithRawResponse

        /** Teams */
        fun invites(): InviteService.WithRawResponse

        /**
         * Returns a raw HTTP response for `get /v1/teams`, but is otherwise the same as
         * [TeamService.list].
         */
        @MustBeClosed fun list(): HttpResponseFor<List<Team>> = list(TeamListParams.none())

        /** @see list */
        @MustBeClosed
        fun list(
            params: TeamListParams = TeamListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<Team>>

        /** @see list */
        @MustBeClosed
        fun list(params: TeamListParams): HttpResponseFor<List<Team>> =
            list(params, RequestOptions.none())

        /** @see list */
        @MustBeClosed
        fun list(requestOptions: RequestOptions): HttpResponseFor<List<Team>> =
            list(TeamListParams.none(), requestOptions)
    }
}
