// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.models.scalarDocs

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.scalar.core.ExcludeMissing
import com.scalar.core.JsonField
import com.scalar.core.JsonMissing
import com.scalar.core.JsonValue
import com.scalar.core.checkRequired
import com.scalar.errors.ScalarInvalidDataException
import java.util.Collections
import java.util.Objects

class ActiveDeployment
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val uid: JsonField<String>,
    private val domain: JsonField<String>,
    private val publishedAt: JsonField<Long>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("uid") @ExcludeMissing uid: JsonField<String> = JsonMissing.of(),
        @JsonProperty("domain") @ExcludeMissing domain: JsonField<String> = JsonMissing.of(),
        @JsonProperty("publishedAt")
        @ExcludeMissing
        publishedAt: JsonField<Long> = JsonMissing.of(),
    ) : this(uid, domain, publishedAt, mutableMapOf())

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun uid(): String = uid.getRequired("uid")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun domain(): String = domain.getRequired("domain")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun publishedAt(): Long = publishedAt.getRequired("publishedAt")

    /**
     * Returns the raw JSON value of [uid].
     *
     * Unlike [uid], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("uid") @ExcludeMissing fun _uid(): JsonField<String> = uid

    /**
     * Returns the raw JSON value of [domain].
     *
     * Unlike [domain], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("domain") @ExcludeMissing fun _domain(): JsonField<String> = domain

    /**
     * Returns the raw JSON value of [publishedAt].
     *
     * Unlike [publishedAt], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("publishedAt") @ExcludeMissing fun _publishedAt(): JsonField<Long> = publishedAt

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [ActiveDeployment].
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .domain()
         * .publishedAt()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [ActiveDeployment]. */
    class Builder internal constructor() {

        private var uid: JsonField<String>? = null
        private var domain: JsonField<String>? = null
        private var publishedAt: JsonField<Long>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(activeDeployment: ActiveDeployment) = apply {
            uid = activeDeployment.uid
            domain = activeDeployment.domain
            publishedAt = activeDeployment.publishedAt
            additionalProperties = activeDeployment.additionalProperties.toMutableMap()
        }

        fun uid(uid: String) = uid(JsonField.of(uid))

        /**
         * Sets [Builder.uid] to an arbitrary JSON value.
         *
         * You should usually call [Builder.uid] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun uid(uid: JsonField<String>) = apply { this.uid = uid }

        fun domain(domain: String) = domain(JsonField.of(domain))

        /**
         * Sets [Builder.domain] to an arbitrary JSON value.
         *
         * You should usually call [Builder.domain] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun domain(domain: JsonField<String>) = apply { this.domain = domain }

        fun publishedAt(publishedAt: Long) = publishedAt(JsonField.of(publishedAt))

        /**
         * Sets [Builder.publishedAt] to an arbitrary JSON value.
         *
         * You should usually call [Builder.publishedAt] with a well-typed [Long] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun publishedAt(publishedAt: JsonField<Long>) = apply { this.publishedAt = publishedAt }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [ActiveDeployment].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .domain()
         * .publishedAt()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): ActiveDeployment =
            ActiveDeployment(
                checkRequired("uid", uid),
                checkRequired("domain", domain),
                checkRequired("publishedAt", publishedAt),
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws ScalarInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): ActiveDeployment = apply {
        if (validated) {
            return@apply
        }

        uid()
        domain()
        publishedAt()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: ScalarInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (uid.asKnown().isPresent) 1 else 0) +
            (if (domain.asKnown().isPresent) 1 else 0) +
            (if (publishedAt.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is ActiveDeployment &&
            uid == other.uid &&
            domain == other.domain &&
            publishedAt == other.publishedAt &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(uid, domain, publishedAt, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "ActiveDeployment{uid=$uid, domain=$domain, publishedAt=$publishedAt, additionalProperties=$additionalProperties}"
}
