// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.models.scalarDocs

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.scalar.core.ExcludeMissing
import com.scalar.core.JsonField
import com.scalar.core.JsonMissing
import com.scalar.core.JsonValue
import com.scalar.core.Params
import com.scalar.core.http.Headers
import com.scalar.core.http.QueryParams
import com.scalar.errors.ScalarInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

/** Start a build and deploy. The returned `publishUid` identifies the publish record. */
class ScalarDocPublishProjectParams
private constructor(
    private val slug: String?,
    private val body: Body,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
) : Params {

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun commitSha(): Optional<String> = body.commitSha()

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun preview(): Optional<Boolean> = body.preview()

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun configPath(): Optional<String> = body.configPath()

    fun slug(): Optional<String> = Optional.ofNullable(slug)

    /**
     * Returns the raw JSON value of [commitSha].
     *
     * Unlike [commitSha], this method doesn't throw if the JSON field has an unexpected type.
     */
    fun _commitSha(): JsonField<String> = body._commitSha()

    /**
     * Returns the raw JSON value of [preview].
     *
     * Unlike [preview], this method doesn't throw if the JSON field has an unexpected type.
     */
    fun _preview(): JsonField<Boolean> = body._preview()

    /**
     * Returns the raw JSON value of [configPath].
     *
     * Unlike [configPath], this method doesn't throw if the JSON field has an unexpected type.
     */
    fun _configPath(): JsonField<String> = body._configPath()

    fun _additionalBodyProperties(): Map<String, JsonValue> = body._additionalProperties()

    /** Additional headers to send with the request. */
    fun _additionalHeaders(): Headers = additionalHeaders

    /** Additional query param to send with the request. */
    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun toBuilder() = Builder().from(this)

    companion object {

        @JvmStatic fun none(): ScalarDocPublishProjectParams = builder().build()

        /**
         * Returns a mutable builder for constructing an instance of
         * [ScalarDocPublishProjectParams].
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [ScalarDocPublishProjectParams]. */
    class Builder internal constructor() {

        private var slug: String? = null
        private var body: Body.Builder = Body.builder()
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()

        @JvmSynthetic
        internal fun from(scalarDocPublishProjectParams: ScalarDocPublishProjectParams) = apply {
            slug = scalarDocPublishProjectParams.slug
            body = scalarDocPublishProjectParams.body.toBuilder()
            additionalHeaders = scalarDocPublishProjectParams.additionalHeaders.toBuilder()
            additionalQueryParams = scalarDocPublishProjectParams.additionalQueryParams.toBuilder()
        }

        fun slug(slug: String?) = apply { this.slug = slug }

        /** Alias for calling [Builder.slug] with `slug.orElse(null)`. */
        fun slug(slug: Optional<String>) = slug(slug.getOrNull())

        /**
         * Sets the entire request body.
         *
         * This is generally only useful if you are already constructing the body separately.
         * Otherwise, it's more convenient to use the top-level setters instead:
         * - [commitSha]
         * - [preview]
         * - [configPath]
         */
        fun body(body: Body) = apply { this.body = body.toBuilder() }

        fun commitSha(commitSha: String) = apply { body.commitSha(commitSha) }

        /**
         * Sets [Builder.commitSha] to an arbitrary JSON value.
         *
         * You should usually call [Builder.commitSha] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun commitSha(commitSha: JsonField<String>) = apply { body.commitSha(commitSha) }

        fun preview(preview: Boolean) = apply { body.preview(preview) }

        /**
         * Sets [Builder.preview] to an arbitrary JSON value.
         *
         * You should usually call [Builder.preview] with a well-typed [Boolean] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun preview(preview: JsonField<Boolean>) = apply { body.preview(preview) }

        fun configPath(configPath: String) = apply { body.configPath(configPath) }

        /**
         * Sets [Builder.configPath] to an arbitrary JSON value.
         *
         * You should usually call [Builder.configPath] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun configPath(configPath: JsonField<String>) = apply { body.configPath(configPath) }

        fun additionalBodyProperties(additionalBodyProperties: Map<String, JsonValue>) = apply {
            body.additionalProperties(additionalBodyProperties)
        }

        fun putAdditionalBodyProperty(key: String, value: JsonValue) = apply {
            body.putAdditionalProperty(key, value)
        }

        fun putAllAdditionalBodyProperties(additionalBodyProperties: Map<String, JsonValue>) =
            apply {
                body.putAllAdditionalProperties(additionalBodyProperties)
            }

        fun removeAdditionalBodyProperty(key: String) = apply { body.removeAdditionalProperty(key) }

        fun removeAllAdditionalBodyProperties(keys: Set<String>) = apply {
            body.removeAllAdditionalProperties(keys)
        }

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        /**
         * Returns an immutable instance of [ScalarDocPublishProjectParams].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): ScalarDocPublishProjectParams =
            ScalarDocPublishProjectParams(
                slug,
                body.build(),
                additionalHeaders.build(),
                additionalQueryParams.build(),
            )
    }

    fun _body(): Body = body

    fun _pathParam(index: Int): String =
        when (index) {
            0 -> slug ?: ""
            else -> ""
        }

    override fun _headers(): Headers = additionalHeaders

    override fun _queryParams(): QueryParams = additionalQueryParams

    class Body
    @JsonCreator(mode = JsonCreator.Mode.DISABLED)
    private constructor(
        private val commitSha: JsonField<String>,
        private val preview: JsonField<Boolean>,
        private val configPath: JsonField<String>,
        private val additionalProperties: MutableMap<String, JsonValue>,
    ) {

        @JsonCreator
        private constructor(
            @JsonProperty("commitSha")
            @ExcludeMissing
            commitSha: JsonField<String> = JsonMissing.of(),
            @JsonProperty("preview") @ExcludeMissing preview: JsonField<Boolean> = JsonMissing.of(),
            @JsonProperty("configPath")
            @ExcludeMissing
            configPath: JsonField<String> = JsonMissing.of(),
        ) : this(commitSha, preview, configPath, mutableMapOf())

        /**
         * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
         *   server responded with an unexpected value).
         */
        fun commitSha(): Optional<String> = commitSha.getOptional("commitSha")

        /**
         * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
         *   server responded with an unexpected value).
         */
        fun preview(): Optional<Boolean> = preview.getOptional("preview")

        /**
         * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
         *   server responded with an unexpected value).
         */
        fun configPath(): Optional<String> = configPath.getOptional("configPath")

        /**
         * Returns the raw JSON value of [commitSha].
         *
         * Unlike [commitSha], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("commitSha") @ExcludeMissing fun _commitSha(): JsonField<String> = commitSha

        /**
         * Returns the raw JSON value of [preview].
         *
         * Unlike [preview], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("preview") @ExcludeMissing fun _preview(): JsonField<Boolean> = preview

        /**
         * Returns the raw JSON value of [configPath].
         *
         * Unlike [configPath], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("configPath")
        @ExcludeMissing
        fun _configPath(): JsonField<String> = configPath

        @JsonAnySetter
        private fun putAdditionalProperty(key: String, value: JsonValue) {
            additionalProperties.put(key, value)
        }

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> =
            Collections.unmodifiableMap(additionalProperties)

        fun toBuilder() = Builder().from(this)

        companion object {

            /** Returns a mutable builder for constructing an instance of [Body]. */
            @JvmStatic fun builder() = Builder()
        }

        /** A builder for [Body]. */
        class Builder internal constructor() {

            private var commitSha: JsonField<String> = JsonMissing.of()
            private var preview: JsonField<Boolean> = JsonMissing.of()
            private var configPath: JsonField<String> = JsonMissing.of()
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            @JvmSynthetic
            internal fun from(body: Body) = apply {
                commitSha = body.commitSha
                preview = body.preview
                configPath = body.configPath
                additionalProperties = body.additionalProperties.toMutableMap()
            }

            fun commitSha(commitSha: String) = commitSha(JsonField.of(commitSha))

            /**
             * Sets [Builder.commitSha] to an arbitrary JSON value.
             *
             * You should usually call [Builder.commitSha] with a well-typed [String] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun commitSha(commitSha: JsonField<String>) = apply { this.commitSha = commitSha }

            fun preview(preview: Boolean) = preview(JsonField.of(preview))

            /**
             * Sets [Builder.preview] to an arbitrary JSON value.
             *
             * You should usually call [Builder.preview] with a well-typed [Boolean] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun preview(preview: JsonField<Boolean>) = apply { this.preview = preview }

            fun configPath(configPath: String) = configPath(JsonField.of(configPath))

            /**
             * Sets [Builder.configPath] to an arbitrary JSON value.
             *
             * You should usually call [Builder.configPath] with a well-typed [String] value
             * instead. This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun configPath(configPath: JsonField<String>) = apply { this.configPath = configPath }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                putAllAdditionalProperties(additionalProperties)
            }

            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

            fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                keys.forEach(::removeAdditionalProperty)
            }

            /**
             * Returns an immutable instance of [Body].
             *
             * Further updates to this [Builder] will not mutate the returned instance.
             */
            fun build(): Body =
                Body(commitSha, preview, configPath, additionalProperties.toMutableMap())
        }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws ScalarInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): Body = apply {
            if (validated) {
                return@apply
            }

            commitSha()
            preview()
            configPath()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: ScalarInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        @JvmSynthetic
        internal fun validity(): Int =
            (if (commitSha.asKnown().isPresent) 1 else 0) +
                (if (preview.asKnown().isPresent) 1 else 0) +
                (if (configPath.asKnown().isPresent) 1 else 0)

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Body &&
                commitSha == other.commitSha &&
                preview == other.preview &&
                configPath == other.configPath &&
                additionalProperties == other.additionalProperties
        }

        private val hashCode: Int by lazy {
            Objects.hash(commitSha, preview, configPath, additionalProperties)
        }

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "Body{commitSha=$commitSha, preview=$preview, configPath=$configPath, additionalProperties=$additionalProperties}"
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is ScalarDocPublishProjectParams &&
            slug == other.slug &&
            body == other.body &&
            additionalHeaders == other.additionalHeaders &&
            additionalQueryParams == other.additionalQueryParams
    }

    override fun hashCode(): Int =
        Objects.hash(slug, body, additionalHeaders, additionalQueryParams)

    override fun toString() =
        "ScalarDocPublishProjectParams{slug=$slug, body=$body, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams}"
}
