// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.models.scalarDocs

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.scalar.core.ExcludeMissing
import com.scalar.core.JsonField
import com.scalar.core.JsonMissing
import com.scalar.core.JsonValue
import com.scalar.core.checkRequired
import com.scalar.errors.ScalarInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

class ScalarDocListProjectDomainResponse
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val scalarDomain: JsonField<String>,
    private val customDomain: JsonField<String>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("scalarDomain")
        @ExcludeMissing
        scalarDomain: JsonField<String> = JsonMissing.of(),
        @JsonProperty("customDomain")
        @ExcludeMissing
        customDomain: JsonField<String> = JsonMissing.of(),
    ) : this(scalarDomain, customDomain, mutableMapOf())

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun scalarDomain(): Optional<String> = scalarDomain.getOptional("scalarDomain")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun customDomain(): Optional<String> = customDomain.getOptional("customDomain")

    /**
     * Returns the raw JSON value of [scalarDomain].
     *
     * Unlike [scalarDomain], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("scalarDomain")
    @ExcludeMissing
    fun _scalarDomain(): JsonField<String> = scalarDomain

    /**
     * Returns the raw JSON value of [customDomain].
     *
     * Unlike [customDomain], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("customDomain")
    @ExcludeMissing
    fun _customDomain(): JsonField<String> = customDomain

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of
         * [ScalarDocListProjectDomainResponse].
         *
         * The following fields are required:
         * ```kotlin
         * .scalarDomain()
         * .customDomain()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [ScalarDocListProjectDomainResponse]. */
    class Builder internal constructor() {

        private var scalarDomain: JsonField<String>? = null
        private var customDomain: JsonField<String>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(scalarDocListProjectDomainResponse: ScalarDocListProjectDomainResponse) =
            apply {
                scalarDomain = scalarDocListProjectDomainResponse.scalarDomain
                customDomain = scalarDocListProjectDomainResponse.customDomain
                additionalProperties =
                    scalarDocListProjectDomainResponse.additionalProperties.toMutableMap()
            }

        fun scalarDomain(scalarDomain: String?) = scalarDomain(JsonField.ofNullable(scalarDomain))

        /** Alias for calling [Builder.scalarDomain] with `scalarDomain.orElse(null)`. */
        fun scalarDomain(scalarDomain: Optional<String>) = scalarDomain(scalarDomain.getOrNull())

        /**
         * Sets [Builder.scalarDomain] to an arbitrary JSON value.
         *
         * You should usually call [Builder.scalarDomain] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun scalarDomain(scalarDomain: JsonField<String>) = apply {
            this.scalarDomain = scalarDomain
        }

        fun customDomain(customDomain: String?) = customDomain(JsonField.ofNullable(customDomain))

        /** Alias for calling [Builder.customDomain] with `customDomain.orElse(null)`. */
        fun customDomain(customDomain: Optional<String>) = customDomain(customDomain.getOrNull())

        /**
         * Sets [Builder.customDomain] to an arbitrary JSON value.
         *
         * You should usually call [Builder.customDomain] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun customDomain(customDomain: JsonField<String>) = apply {
            this.customDomain = customDomain
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [ScalarDocListProjectDomainResponse].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .scalarDomain()
         * .customDomain()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): ScalarDocListProjectDomainResponse =
            ScalarDocListProjectDomainResponse(
                checkRequired("scalarDomain", scalarDomain),
                checkRequired("customDomain", customDomain),
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws ScalarInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): ScalarDocListProjectDomainResponse = apply {
        if (validated) {
            return@apply
        }

        scalarDomain()
        customDomain()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: ScalarInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (scalarDomain.asKnown().isPresent) 1 else 0) +
            (if (customDomain.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is ScalarDocListProjectDomainResponse &&
            scalarDomain == other.scalarDomain &&
            customDomain == other.customDomain &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(scalarDomain, customDomain, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "ScalarDocListProjectDomainResponse{scalarDomain=$scalarDomain, customDomain=$customDomain, additionalProperties=$additionalProperties}"
}
