// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.client

import com.scalar.core.ClientOptions
import com.scalar.core.getPackageVersion
import com.scalar.services.async.AuthenticationServiceAsync
import com.scalar.services.async.AuthenticationServiceAsyncImpl
import com.scalar.services.async.LoginPortalServiceAsync
import com.scalar.services.async.LoginPortalServiceAsyncImpl
import com.scalar.services.async.NamespaceServiceAsync
import com.scalar.services.async.NamespaceServiceAsyncImpl
import com.scalar.services.async.RegistryServiceAsync
import com.scalar.services.async.RegistryServiceAsyncImpl
import com.scalar.services.async.RuleServiceAsync
import com.scalar.services.async.RuleServiceAsyncImpl
import com.scalar.services.async.ScalarDocServiceAsync
import com.scalar.services.async.ScalarDocServiceAsyncImpl
import com.scalar.services.async.SchemaServiceAsync
import com.scalar.services.async.SchemaServiceAsyncImpl
import com.scalar.services.async.TeamServiceAsync
import com.scalar.services.async.TeamServiceAsyncImpl
import com.scalar.services.async.ThemeServiceAsync
import com.scalar.services.async.ThemeServiceAsyncImpl
import java.util.function.Consumer

class ScalarClientAsyncImpl(private val clientOptions: ClientOptions) : ScalarClientAsync {

    private val clientOptionsWithUserAgent =
        if (clientOptions.headers.names().contains("User-Agent")) clientOptions
        else
            clientOptions
                .toBuilder()
                .putHeader("User-Agent", "${javaClass.simpleName}/Java ${getPackageVersion()}")
                .build()

    // Pass the original clientOptions so that this client sets its own User-Agent.
    private val sync: ScalarClient by lazy { ScalarClientImpl(clientOptions) }

    private val withRawResponse: ScalarClientAsync.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    private val registry: RegistryServiceAsync by lazy {
        RegistryServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val schemas: SchemaServiceAsync by lazy {
        SchemaServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val loginPortals: LoginPortalServiceAsync by lazy {
        LoginPortalServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val rules: RuleServiceAsync by lazy { RuleServiceAsyncImpl(clientOptionsWithUserAgent) }

    private val themes: ThemeServiceAsync by lazy {
        ThemeServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val teams: TeamServiceAsync by lazy { TeamServiceAsyncImpl(clientOptionsWithUserAgent) }

    private val scalarDocs: ScalarDocServiceAsync by lazy {
        ScalarDocServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val namespaces: NamespaceServiceAsync by lazy {
        NamespaceServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val authentication: AuthenticationServiceAsync by lazy {
        AuthenticationServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    override fun sync(): ScalarClient = sync

    override fun withRawResponse(): ScalarClientAsync.WithRawResponse = withRawResponse

    override fun withOptions(modifier: Consumer<ClientOptions.Builder>): ScalarClientAsync =
        ScalarClientAsyncImpl(clientOptions.toBuilder().apply(modifier::accept).build())

    /** Registry */
    override fun registry(): RegistryServiceAsync = registry

    /** Schemas */
    override fun schemas(): SchemaServiceAsync = schemas

    /** Login Portals */
    override fun loginPortals(): LoginPortalServiceAsync = loginPortals

    /** Rules */
    override fun rules(): RuleServiceAsync = rules

    /** Themes */
    override fun themes(): ThemeServiceAsync = themes

    /** Teams */
    override fun teams(): TeamServiceAsync = teams

    /** Scalar Docs */
    override fun scalarDocs(): ScalarDocServiceAsync = scalarDocs

    /** Namespaces */
    override fun namespaces(): NamespaceServiceAsync = namespaces

    /** Authentication */
    override fun authentication(): AuthenticationServiceAsync = authentication

    override fun close() = clientOptions.close()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        ScalarClientAsync.WithRawResponse {

        private val registry: RegistryServiceAsync.WithRawResponse by lazy {
            RegistryServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val schemas: SchemaServiceAsync.WithRawResponse by lazy {
            SchemaServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val loginPortals: LoginPortalServiceAsync.WithRawResponse by lazy {
            LoginPortalServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val rules: RuleServiceAsync.WithRawResponse by lazy {
            RuleServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val themes: ThemeServiceAsync.WithRawResponse by lazy {
            ThemeServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val teams: TeamServiceAsync.WithRawResponse by lazy {
            TeamServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val scalarDocs: ScalarDocServiceAsync.WithRawResponse by lazy {
            ScalarDocServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val namespaces: NamespaceServiceAsync.WithRawResponse by lazy {
            NamespaceServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val authentication: AuthenticationServiceAsync.WithRawResponse by lazy {
            AuthenticationServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        override fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): ScalarClientAsync.WithRawResponse =
            ScalarClientAsyncImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier::accept).build()
            )

        /** Registry */
        override fun registry(): RegistryServiceAsync.WithRawResponse = registry

        /** Schemas */
        override fun schemas(): SchemaServiceAsync.WithRawResponse = schemas

        /** Login Portals */
        override fun loginPortals(): LoginPortalServiceAsync.WithRawResponse = loginPortals

        /** Rules */
        override fun rules(): RuleServiceAsync.WithRawResponse = rules

        /** Themes */
        override fun themes(): ThemeServiceAsync.WithRawResponse = themes

        /** Teams */
        override fun teams(): TeamServiceAsync.WithRawResponse = teams

        /** Scalar Docs */
        override fun scalarDocs(): ScalarDocServiceAsync.WithRawResponse = scalarDocs

        /** Namespaces */
        override fun namespaces(): NamespaceServiceAsync.WithRawResponse = namespaces

        /** Authentication */
        override fun authentication(): AuthenticationServiceAsync.WithRawResponse = authentication
    }
}
