// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async.schemas

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.checkRequired
import com.scalar.core.handlers.errorBodyHandler
import com.scalar.core.handlers.errorHandler
import com.scalar.core.handlers.jsonHandler
import com.scalar.core.http.HttpMethod
import com.scalar.core.http.HttpRequest
import com.scalar.core.http.HttpResponse
import com.scalar.core.http.HttpResponse.Handler
import com.scalar.core.http.HttpResponseFor
import com.scalar.core.http.json
import com.scalar.core.http.parseable
import com.scalar.core.prepareAsync
import com.scalar.models.schemas.accessGroup.AccessGroupCreateParams
import com.scalar.models.schemas.accessGroup.AccessGroupDeleteParams
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer
import kotlin.jvm.optionals.getOrNull

/** Schemas */
class AccessGroupServiceAsyncImpl internal constructor(private val clientOptions: ClientOptions) :
    AccessGroupServiceAsync {

    private val withRawResponse: AccessGroupServiceAsync.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): AccessGroupServiceAsync.WithRawResponse = withRawResponse

    override fun withOptions(modifier: Consumer<ClientOptions.Builder>): AccessGroupServiceAsync =
        AccessGroupServiceAsyncImpl(clientOptions.toBuilder().apply(modifier::accept).build())

    override fun create(
        params: AccessGroupCreateParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Any?> =
        // post /v1/schemas/{namespace}/{slug}/access-group
        withRawResponse().create(params, requestOptions).thenApply { it.parse() }

    override fun delete(
        params: AccessGroupDeleteParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Any?> =
        // delete /v1/schemas/{namespace}/{slug}/access-group
        withRawResponse().delete(params, requestOptions).thenApply { it.parse() }

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        AccessGroupServiceAsync.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): AccessGroupServiceAsync.WithRawResponse =
            AccessGroupServiceAsyncImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier::accept).build()
            )

        private val createHandler: Handler<Any?> = jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun create(
            params: AccessGroupCreateParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments(
                        "v1",
                        "schemas",
                        params._pathParam(0),
                        params._pathParam(1),
                        "access-group",
                    )
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { createHandler.handle(it) }
                    }
                }
        }

        private val deleteHandler: Handler<Any?> = jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun delete(
            params: AccessGroupDeleteParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.DELETE)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments(
                        "v1",
                        "schemas",
                        params._pathParam(0),
                        params._pathParam(1),
                        "access-group",
                    )
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { deleteHandler.handle(it) }
                    }
                }
        }
    }
}
