// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async.schemas

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.Uid
import com.scalar.models.schemas.version.VersionCreateParams
import com.scalar.models.schemas.version.VersionDeleteParams
import com.scalar.models.schemas.version.VersionRetrieveParams
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

/** Schemas */
interface VersionServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): VersionServiceAsync

    /** Create a schema version. */
    fun create(slug: String, params: VersionCreateParams): CompletableFuture<Uid> =
        create(slug, params, RequestOptions.none())

    /** @see create */
    fun create(
        slug: String,
        params: VersionCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Uid> = create(params.toBuilder().slug(slug).build(), requestOptions)

    /** @see create */
    fun create(
        params: VersionCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Uid>

    /** @see create */
    fun create(params: VersionCreateParams): CompletableFuture<Uid> =
        create(params, RequestOptions.none())

    /** Get a specific schema version document. */
    fun retrieve(semver: String, params: VersionRetrieveParams): CompletableFuture<String> =
        retrieve(semver, params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(
        semver: String,
        params: VersionRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<String> =
        retrieve(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see retrieve */
    fun retrieve(
        params: VersionRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<String>

    /** @see retrieve */
    fun retrieve(params: VersionRetrieveParams): CompletableFuture<String> =
        retrieve(params, RequestOptions.none())

    /** Delete a schema version. */
    fun delete(semver: String, params: VersionDeleteParams): CompletableFuture<Any?> =
        delete(semver, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        semver: String,
        params: VersionDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> = delete(params.toBuilder().semver(semver).build(), requestOptions)

    /** @see delete */
    fun delete(
        params: VersionDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see delete */
    fun delete(params: VersionDeleteParams): CompletableFuture<Any?> =
        delete(params, RequestOptions.none())

    /**
     * A view of [VersionServiceAsync] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): VersionServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/schemas/{namespace}/{slug}/version`, but is
         * otherwise the same as [VersionServiceAsync.create].
         */
        fun create(
            slug: String,
            params: VersionCreateParams,
        ): CompletableFuture<HttpResponseFor<Uid>> = create(slug, params, RequestOptions.none())

        /** @see create */
        fun create(
            slug: String,
            params: VersionCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Uid>> =
            create(params.toBuilder().slug(slug).build(), requestOptions)

        /** @see create */
        fun create(
            params: VersionCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Uid>>

        /** @see create */
        fun create(params: VersionCreateParams): CompletableFuture<HttpResponseFor<Uid>> =
            create(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `get /v1/schemas/{namespace}/{slug}/version/{semver}`,
         * but is otherwise the same as [VersionServiceAsync.retrieve].
         */
        fun retrieve(
            semver: String,
            params: VersionRetrieveParams,
        ): CompletableFuture<HttpResponseFor<String>> =
            retrieve(semver, params, RequestOptions.none())

        /** @see retrieve */
        fun retrieve(
            semver: String,
            params: VersionRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<String>> =
            retrieve(params.toBuilder().semver(semver).build(), requestOptions)

        /** @see retrieve */
        fun retrieve(
            params: VersionRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<String>>

        /** @see retrieve */
        fun retrieve(params: VersionRetrieveParams): CompletableFuture<HttpResponseFor<String>> =
            retrieve(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `delete /v1/schemas/{namespace}/{slug}/version/{semver}`,
         * but is otherwise the same as [VersionServiceAsync.delete].
         */
        fun delete(
            semver: String,
            params: VersionDeleteParams,
        ): CompletableFuture<HttpResponseFor<Any?>> = delete(semver, params, RequestOptions.none())

        /** @see delete */
        fun delete(
            semver: String,
            params: VersionDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params.toBuilder().semver(semver).build(), requestOptions)

        /** @see delete */
        fun delete(
            params: VersionDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see delete */
        fun delete(params: VersionDeleteParams): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params, RequestOptions.none())
    }
}
