// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.oAuth.OAuthOauthAuthorizationServerMetadataParams
import com.scalar.models.oAuth.OAuthOauthAuthorizeParams
import com.scalar.models.oAuth.OAuthOauthRevokeParams
import com.scalar.models.oAuth.OAuthOauthTokenParams
import com.scalar.models.oAuth.OAuthOauthTokenResponse
import com.scalar.models.oAuth.OauthAuthorizationServerMetadata
import com.scalar.models.oAuth.OauthError
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

/** OAuth */
interface OAuthServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): OAuthServiceAsync

    /**
     * Discovery document for OAuth clients (RFC 8414): where the endpoints are and what they
     * support.
     */
    fun oauthAuthorizationServerMetadata(): CompletableFuture<OauthAuthorizationServerMetadata> =
        oauthAuthorizationServerMetadata(OAuthOauthAuthorizationServerMetadataParams.none())

    /** @see oauthAuthorizationServerMetadata */
    fun oauthAuthorizationServerMetadata(
        params: OAuthOauthAuthorizationServerMetadataParams =
            OAuthOauthAuthorizationServerMetadataParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<OauthAuthorizationServerMetadata>

    /** @see oauthAuthorizationServerMetadata */
    fun oauthAuthorizationServerMetadata(
        params: OAuthOauthAuthorizationServerMetadataParams
    ): CompletableFuture<OauthAuthorizationServerMetadata> =
        oauthAuthorizationServerMetadata(params, RequestOptions.none())

    /** @see oauthAuthorizationServerMetadata */
    fun oauthAuthorizationServerMetadata(
        requestOptions: RequestOptions
    ): CompletableFuture<OauthAuthorizationServerMetadata> =
        oauthAuthorizationServerMetadata(
            OAuthOauthAuthorizationServerMetadataParams.none(),
            requestOptions,
        )

    /**
     * Authorization endpoint (RFC 6749 §4.1.1 with PKCE, RFC 7636). Validates the request and sends
     * the user to the Scalar dashboard to approve it; the user returns to `redirect_uri` with a
     * `code` to exchange at the token endpoint. Only `response_type=code` with
     * `code_challenge_method=S256` is supported.
     */
    fun oauthAuthorize(): CompletableFuture<Any?> = oauthAuthorize(OAuthOauthAuthorizeParams.none())

    /** @see oauthAuthorize */
    fun oauthAuthorize(
        params: OAuthOauthAuthorizeParams = OAuthOauthAuthorizeParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see oauthAuthorize */
    fun oauthAuthorize(params: OAuthOauthAuthorizeParams): CompletableFuture<Any?> =
        oauthAuthorize(params, RequestOptions.none())

    /** @see oauthAuthorize */
    fun oauthAuthorize(requestOptions: RequestOptions): CompletableFuture<Any?> =
        oauthAuthorize(OAuthOauthAuthorizeParams.none(), requestOptions)

    /**
     * Revocation endpoint (RFC 7009). Revokes the refresh token and every token issued alongside
     * it. The client authenticates as it does at the token endpoint. Responds 200 whether or not
     * the token was live, as the RFC requires.
     */
    fun oauthRevoke(params: OAuthOauthRevokeParams): CompletableFuture<OauthError?> =
        oauthRevoke(params, RequestOptions.none())

    /** @see oauthRevoke */
    fun oauthRevoke(
        params: OAuthOauthRevokeParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<OauthError?>

    /**
     * Token endpoint (RFC 6749 §4.1.3 and §6). Accepts `application/x-www-form-urlencoded`.
     * Confidential clients authenticate with HTTP Basic or `client_secret` in the body; public
     * clients send `client_id` alone. The `authorization_code` grant needs `code`, `redirect_uri`
     * and `code_verifier`; the `refresh_token` grant needs `refresh_token` and may narrow `scope`.
     */
    fun oauthToken(params: OAuthOauthTokenParams): CompletableFuture<OAuthOauthTokenResponse> =
        oauthToken(params, RequestOptions.none())

    /** @see oauthToken */
    fun oauthToken(
        params: OAuthOauthTokenParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<OAuthOauthTokenResponse>

    /** A view of [OAuthServiceAsync] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): OAuthServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `get /.well-known/oauth-authorization-server`, but is
         * otherwise the same as [OAuthServiceAsync.oauthAuthorizationServerMetadata].
         */
        fun oauthAuthorizationServerMetadata():
            CompletableFuture<HttpResponseFor<OauthAuthorizationServerMetadata>> =
            oauthAuthorizationServerMetadata(OAuthOauthAuthorizationServerMetadataParams.none())

        /** @see oauthAuthorizationServerMetadata */
        fun oauthAuthorizationServerMetadata(
            params: OAuthOauthAuthorizationServerMetadataParams =
                OAuthOauthAuthorizationServerMetadataParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<OauthAuthorizationServerMetadata>>

        /** @see oauthAuthorizationServerMetadata */
        fun oauthAuthorizationServerMetadata(
            params: OAuthOauthAuthorizationServerMetadataParams
        ): CompletableFuture<HttpResponseFor<OauthAuthorizationServerMetadata>> =
            oauthAuthorizationServerMetadata(params, RequestOptions.none())

        /** @see oauthAuthorizationServerMetadata */
        fun oauthAuthorizationServerMetadata(
            requestOptions: RequestOptions
        ): CompletableFuture<HttpResponseFor<OauthAuthorizationServerMetadata>> =
            oauthAuthorizationServerMetadata(
                OAuthOauthAuthorizationServerMetadataParams.none(),
                requestOptions,
            )

        /**
         * Returns a raw HTTP response for `get /v1/oauth/authorize`, but is otherwise the same as
         * [OAuthServiceAsync.oauthAuthorize].
         */
        fun oauthAuthorize(): CompletableFuture<HttpResponseFor<Any?>> =
            oauthAuthorize(OAuthOauthAuthorizeParams.none())

        /** @see oauthAuthorize */
        fun oauthAuthorize(
            params: OAuthOauthAuthorizeParams = OAuthOauthAuthorizeParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see oauthAuthorize */
        fun oauthAuthorize(
            params: OAuthOauthAuthorizeParams
        ): CompletableFuture<HttpResponseFor<Any?>> = oauthAuthorize(params, RequestOptions.none())

        /** @see oauthAuthorize */
        fun oauthAuthorize(
            requestOptions: RequestOptions
        ): CompletableFuture<HttpResponseFor<Any?>> =
            oauthAuthorize(OAuthOauthAuthorizeParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `post /v1/oauth/revoke`, but is otherwise the same as
         * [OAuthServiceAsync.oauthRevoke].
         */
        fun oauthRevoke(
            params: OAuthOauthRevokeParams
        ): CompletableFuture<HttpResponseFor<OauthError?>> =
            oauthRevoke(params, RequestOptions.none())

        /** @see oauthRevoke */
        fun oauthRevoke(
            params: OAuthOauthRevokeParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<OauthError?>>

        /**
         * Returns a raw HTTP response for `post /v1/oauth/token`, but is otherwise the same as
         * [OAuthServiceAsync.oauthToken].
         */
        fun oauthToken(
            params: OAuthOauthTokenParams
        ): CompletableFuture<HttpResponseFor<OAuthOauthTokenResponse>> =
            oauthToken(params, RequestOptions.none())

        /** @see oauthToken */
        fun oauthToken(
            params: OAuthOauthTokenParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<OAuthOauthTokenResponse>>
    }
}
