// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.Uid
import com.scalar.models.sdks.Sdk
import com.scalar.models.sdks.SdkBuildParams
import com.scalar.models.sdks.SdkBuildResponse
import com.scalar.models.sdks.SdkCreateParams
import com.scalar.models.sdks.SdkDeleteParams
import com.scalar.models.sdks.SdkListParams
import com.scalar.models.sdks.SdkListResponse
import com.scalar.models.sdks.SdkRetrieveParams
import com.scalar.models.sdks.SdkUpdateParams
import com.scalar.services.async.sdks.RepositoryServiceAsync
import com.scalar.services.async.sdks.VersionServiceAsync
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

/** SDKs */
interface SdkServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): SdkServiceAsync

    /** SDKs */
    fun versions(): VersionServiceAsync

    /** SDKs */
    fun repositories(): RepositoryServiceAsync

    /** Create an SDK from an API document, targeting one or more languages. */
    fun create(params: SdkCreateParams): CompletableFuture<Uid> =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(
        params: SdkCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Uid>

    /** Get a single SDK by its uid. */
    fun retrieve(uid: String): CompletableFuture<Sdk> = retrieve(uid, SdkRetrieveParams.none())

    /** @see retrieve */
    fun retrieve(
        uid: String,
        params: SdkRetrieveParams = SdkRetrieveParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Sdk> = retrieve(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see retrieve */
    fun retrieve(uid: String, params: SdkRetrieveParams): CompletableFuture<Sdk> =
        retrieve(uid, params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(
        params: SdkRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Sdk>

    /** @see retrieve */
    fun retrieve(params: SdkRetrieveParams): CompletableFuture<Sdk> =
        retrieve(params, RequestOptions.none())

    /** @see retrieve */
    fun retrieve(uid: String, requestOptions: RequestOptions): CompletableFuture<Sdk> =
        retrieve(uid, SdkRetrieveParams.none(), requestOptions)

    /** Update SDK metadata, its linked API, or its config. */
    fun update(uid: String): CompletableFuture<Any?> = update(uid, SdkUpdateParams.none())

    /** @see update */
    fun update(
        uid: String,
        params: SdkUpdateParams = SdkUpdateParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> = update(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see update */
    fun update(uid: String, params: SdkUpdateParams): CompletableFuture<Any?> =
        update(uid, params, RequestOptions.none())

    /** @see update */
    fun update(
        params: SdkUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see update */
    fun update(params: SdkUpdateParams): CompletableFuture<Any?> =
        update(params, RequestOptions.none())

    /** @see update */
    fun update(uid: String, requestOptions: RequestOptions): CompletableFuture<Any?> =
        update(uid, SdkUpdateParams.none(), requestOptions)

    /** List every SDK on the team. */
    fun list(): CompletableFuture<SdkListResponse> = list(SdkListParams.none())

    /** @see list */
    fun list(
        params: SdkListParams = SdkListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<SdkListResponse>

    /** @see list */
    fun list(params: SdkListParams): CompletableFuture<SdkListResponse> =
        list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): CompletableFuture<SdkListResponse> =
        list(SdkListParams.none(), requestOptions)

    /** Delete an SDK and every version it holds. */
    fun delete(uid: String): CompletableFuture<Any?> = delete(uid, SdkDeleteParams.none())

    /** @see delete */
    fun delete(
        uid: String,
        params: SdkDeleteParams = SdkDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> = delete(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see delete */
    fun delete(uid: String, params: SdkDeleteParams): CompletableFuture<Any?> =
        delete(uid, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: SdkDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see delete */
    fun delete(params: SdkDeleteParams): CompletableFuture<Any?> =
        delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(uid: String, requestOptions: RequestOptions): CompletableFuture<Any?> =
        delete(uid, SdkDeleteParams.none(), requestOptions)

    /**
     * Start a build. Omit `version` to build the current work — the open draft, else the latest
     * version — and the resolved version comes back in the response.
     */
    fun build(uid: String): CompletableFuture<SdkBuildResponse> = build(uid, SdkBuildParams.none())

    /** @see build */
    fun build(
        uid: String,
        params: SdkBuildParams = SdkBuildParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<SdkBuildResponse> =
        build(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see build */
    fun build(uid: String, params: SdkBuildParams): CompletableFuture<SdkBuildResponse> =
        build(uid, params, RequestOptions.none())

    /** @see build */
    fun build(
        params: SdkBuildParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<SdkBuildResponse>

    /** @see build */
    fun build(params: SdkBuildParams): CompletableFuture<SdkBuildResponse> =
        build(params, RequestOptions.none())

    /** @see build */
    fun build(uid: String, requestOptions: RequestOptions): CompletableFuture<SdkBuildResponse> =
        build(uid, SdkBuildParams.none(), requestOptions)

    /** A view of [SdkServiceAsync] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(modifier: Consumer<ClientOptions.Builder>): SdkServiceAsync.WithRawResponse

        /** SDKs */
        fun versions(): VersionServiceAsync.WithRawResponse

        /** SDKs */
        fun repositories(): RepositoryServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/sdks`, but is otherwise the same as
         * [SdkServiceAsync.create].
         */
        fun create(params: SdkCreateParams): CompletableFuture<HttpResponseFor<Uid>> =
            create(params, RequestOptions.none())

        /** @see create */
        fun create(
            params: SdkCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Uid>>

        /**
         * Returns a raw HTTP response for `get /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkServiceAsync.retrieve].
         */
        fun retrieve(uid: String): CompletableFuture<HttpResponseFor<Sdk>> =
            retrieve(uid, SdkRetrieveParams.none())

        /** @see retrieve */
        fun retrieve(
            uid: String,
            params: SdkRetrieveParams = SdkRetrieveParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Sdk>> =
            retrieve(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see retrieve */
        fun retrieve(
            uid: String,
            params: SdkRetrieveParams,
        ): CompletableFuture<HttpResponseFor<Sdk>> = retrieve(uid, params, RequestOptions.none())

        /** @see retrieve */
        fun retrieve(
            params: SdkRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Sdk>>

        /** @see retrieve */
        fun retrieve(params: SdkRetrieveParams): CompletableFuture<HttpResponseFor<Sdk>> =
            retrieve(params, RequestOptions.none())

        /** @see retrieve */
        fun retrieve(
            uid: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Sdk>> =
            retrieve(uid, SdkRetrieveParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `patch /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkServiceAsync.update].
         */
        fun update(uid: String): CompletableFuture<HttpResponseFor<Any?>> =
            update(uid, SdkUpdateParams.none())

        /** @see update */
        fun update(
            uid: String,
            params: SdkUpdateParams = SdkUpdateParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            update(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see update */
        fun update(uid: String, params: SdkUpdateParams): CompletableFuture<HttpResponseFor<Any?>> =
            update(uid, params, RequestOptions.none())

        /** @see update */
        fun update(
            params: SdkUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see update */
        fun update(params: SdkUpdateParams): CompletableFuture<HttpResponseFor<Any?>> =
            update(params, RequestOptions.none())

        /** @see update */
        fun update(
            uid: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> =
            update(uid, SdkUpdateParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/sdks`, but is otherwise the same as
         * [SdkServiceAsync.list].
         */
        fun list(): CompletableFuture<HttpResponseFor<SdkListResponse>> = list(SdkListParams.none())

        /** @see list */
        fun list(
            params: SdkListParams = SdkListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<SdkListResponse>>

        /** @see list */
        fun list(params: SdkListParams): CompletableFuture<HttpResponseFor<SdkListResponse>> =
            list(params, RequestOptions.none())

        /** @see list */
        fun list(
            requestOptions: RequestOptions
        ): CompletableFuture<HttpResponseFor<SdkListResponse>> =
            list(SdkListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/sdks/{uid}`, but is otherwise the same as
         * [SdkServiceAsync.delete].
         */
        fun delete(uid: String): CompletableFuture<HttpResponseFor<Any?>> =
            delete(uid, SdkDeleteParams.none())

        /** @see delete */
        fun delete(
            uid: String,
            params: SdkDeleteParams = SdkDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see delete */
        fun delete(uid: String, params: SdkDeleteParams): CompletableFuture<HttpResponseFor<Any?>> =
            delete(uid, params, RequestOptions.none())

        /** @see delete */
        fun delete(
            params: SdkDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see delete */
        fun delete(params: SdkDeleteParams): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params, RequestOptions.none())

        /** @see delete */
        fun delete(
            uid: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> =
            delete(uid, SdkDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `post /v1/sdks/{uid}/build`, but is otherwise the same as
         * [SdkServiceAsync.build].
         */
        fun build(uid: String): CompletableFuture<HttpResponseFor<SdkBuildResponse>> =
            build(uid, SdkBuildParams.none())

        /** @see build */
        fun build(
            uid: String,
            params: SdkBuildParams = SdkBuildParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<SdkBuildResponse>> =
            build(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see build */
        fun build(
            uid: String,
            params: SdkBuildParams,
        ): CompletableFuture<HttpResponseFor<SdkBuildResponse>> =
            build(uid, params, RequestOptions.none())

        /** @see build */
        fun build(
            params: SdkBuildParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<SdkBuildResponse>>

        /** @see build */
        fun build(params: SdkBuildParams): CompletableFuture<HttpResponseFor<SdkBuildResponse>> =
            build(params, RequestOptions.none())

        /** @see build */
        fun build(
            uid: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<SdkBuildResponse>> =
            build(uid, SdkBuildParams.none(), requestOptions)
    }
}
