// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.checkRequired
import com.scalar.core.handlers.errorBodyHandler
import com.scalar.core.handlers.errorHandler
import com.scalar.core.handlers.jsonHandler
import com.scalar.core.handlers.stringHandler
import com.scalar.core.http.HttpMethod
import com.scalar.core.http.HttpRequest
import com.scalar.core.http.HttpResponse
import com.scalar.core.http.HttpResponse.Handler
import com.scalar.core.http.HttpResponseFor
import com.scalar.core.http.json
import com.scalar.core.http.parseable
import com.scalar.core.prepareAsync
import com.scalar.models.Uid
import com.scalar.models.themes.ThemeCreateParams
import com.scalar.models.themes.ThemeDeleteParams
import com.scalar.models.themes.ThemeListParams
import com.scalar.models.themes.ThemeListResponse
import com.scalar.models.themes.ThemeReplaceDocumentParams
import com.scalar.models.themes.ThemeRetrieveParams
import com.scalar.models.themes.ThemeUpdateParams
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer
import kotlin.jvm.optionals.getOrNull

/** Themes */
class ThemeServiceAsyncImpl internal constructor(private val clientOptions: ClientOptions) :
    ThemeServiceAsync {

    private val withRawResponse: ThemeServiceAsync.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): ThemeServiceAsync.WithRawResponse = withRawResponse

    override fun withOptions(modifier: Consumer<ClientOptions.Builder>): ThemeServiceAsync =
        ThemeServiceAsyncImpl(clientOptions.toBuilder().apply(modifier::accept).build())

    override fun create(
        params: ThemeCreateParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Uid> =
        // post /v1/themes
        withRawResponse().create(params, requestOptions).thenApply { it.parse() }

    override fun retrieve(
        params: ThemeRetrieveParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<String> =
        // get /v1/themes/{slug}
        withRawResponse().retrieve(params, requestOptions).thenApply { it.parse() }

    override fun update(
        params: ThemeUpdateParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Any?> =
        // patch /v1/themes/{slug}
        withRawResponse().update(params, requestOptions).thenApply { it.parse() }

    override fun list(
        params: ThemeListParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<List<ThemeListResponse>> =
        // get /v1/themes
        withRawResponse().list(params, requestOptions).thenApply { it.parse() }

    override fun delete(
        params: ThemeDeleteParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Any?> =
        // delete /v1/themes/{slug}
        withRawResponse().delete(params, requestOptions).thenApply { it.parse() }

    override fun replaceDocument(
        params: ThemeReplaceDocumentParams,
        requestOptions: RequestOptions,
    ): CompletableFuture<Any?> =
        // put /v1/themes/{slug}
        withRawResponse().replaceDocument(params, requestOptions).thenApply { it.parse() }

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        ThemeServiceAsync.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): ThemeServiceAsync.WithRawResponse =
            ThemeServiceAsyncImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier::accept).build()
            )

        private val createHandler: Handler<Uid> = jsonHandler<Uid>(clientOptions.jsonMapper)

        override fun create(
            params: ThemeCreateParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Uid>> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response
                            .use { createHandler.handle(it) }
                            .also {
                                if (requestOptions.responseValidation!!) {
                                    it.validate()
                                }
                            }
                    }
                }
        }

        private val retrieveHandler: Handler<String> = stringHandler()

        override fun retrieve(
            params: ThemeRetrieveParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<String>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes", params._pathParam(0))
                    .putHeader("Accept", "text/plain")
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { retrieveHandler.handle(it) }
                    }
                }
        }

        private val updateHandler: Handler<Any?> = jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun update(
            params: ThemeUpdateParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.PATCH)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes", params._pathParam(0))
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { updateHandler.handle(it) }
                    }
                }
        }

        private val listHandler: Handler<List<ThemeListResponse>> =
            jsonHandler<List<ThemeListResponse>>(clientOptions.jsonMapper)

        override fun list(
            params: ThemeListParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<List<ThemeListResponse>>> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes")
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response
                            .use { listHandler.handle(it) }
                            .also {
                                if (requestOptions.responseValidation!!) {
                                    it.forEach { it.validate() }
                                }
                            }
                    }
                }
        }

        private val deleteHandler: Handler<Any?> = jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun delete(
            params: ThemeDeleteParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.DELETE)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes", params._pathParam(0))
                    .apply { params._body().ifPresent { body(json(clientOptions.jsonMapper, it)) } }
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { deleteHandler.handle(it) }
                    }
                }
        }

        private val replaceDocumentHandler: Handler<Any?> =
            jsonHandler<Any?>(clientOptions.jsonMapper)

        override fun replaceDocument(
            params: ThemeReplaceDocumentParams,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("slug", params.slug().getOrNull())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.PUT)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("v1", "themes", params._pathParam(0))
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            return request
                .thenComposeAsync { clientOptions.httpClient.executeAsync(it, requestOptions) }
                .thenApply { response ->
                    errorHandler.handle(response).parseable {
                        response.use { replaceDocumentHandler.handle(it) }
                    }
                }
        }
    }
}
