// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.models.teams

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.scalar.core.ExcludeMissing
import com.scalar.core.JsonField
import com.scalar.core.JsonMissing
import com.scalar.core.JsonValue
import com.scalar.core.checkRequired
import com.scalar.errors.ScalarInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional

class TeamListResponse
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val uid: JsonField<String>,
    private val name: JsonField<String>,
    private val imageUri: JsonField<String>,
    private val slug: JsonField<String>,
    private val theme: JsonField<String>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("uid") @ExcludeMissing uid: JsonField<String> = JsonMissing.of(),
        @JsonProperty("name") @ExcludeMissing name: JsonField<String> = JsonMissing.of(),
        @JsonProperty("imageUri") @ExcludeMissing imageUri: JsonField<String> = JsonMissing.of(),
        @JsonProperty("slug") @ExcludeMissing slug: JsonField<String> = JsonMissing.of(),
        @JsonProperty("theme") @ExcludeMissing theme: JsonField<String> = JsonMissing.of(),
    ) : this(uid, name, imageUri, slug, theme, mutableMapOf())

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun uid(): String = uid.getRequired("uid")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun name(): String = name.getRequired("name")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun imageUri(): Optional<String> = imageUri.getOptional("imageUri")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun slug(): String = slug.getRequired("slug")

    /**
     * @throws ScalarInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun theme(): String = theme.getRequired("theme")

    /**
     * Returns the raw JSON value of [uid].
     *
     * Unlike [uid], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("uid") @ExcludeMissing fun _uid(): JsonField<String> = uid

    /**
     * Returns the raw JSON value of [name].
     *
     * Unlike [name], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("name") @ExcludeMissing fun _name(): JsonField<String> = name

    /**
     * Returns the raw JSON value of [imageUri].
     *
     * Unlike [imageUri], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("imageUri") @ExcludeMissing fun _imageUri(): JsonField<String> = imageUri

    /**
     * Returns the raw JSON value of [slug].
     *
     * Unlike [slug], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("slug") @ExcludeMissing fun _slug(): JsonField<String> = slug

    /**
     * Returns the raw JSON value of [theme].
     *
     * Unlike [theme], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("theme") @ExcludeMissing fun _theme(): JsonField<String> = theme

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [TeamListResponse].
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .name()
         * .slug()
         * .theme()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [TeamListResponse]. */
    class Builder internal constructor() {

        private var uid: JsonField<String>? = null
        private var name: JsonField<String>? = null
        private var imageUri: JsonField<String> = JsonMissing.of()
        private var slug: JsonField<String>? = null
        private var theme: JsonField<String>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(teamListResponse: TeamListResponse) = apply {
            uid = teamListResponse.uid
            name = teamListResponse.name
            imageUri = teamListResponse.imageUri
            slug = teamListResponse.slug
            theme = teamListResponse.theme
            additionalProperties = teamListResponse.additionalProperties.toMutableMap()
        }

        fun uid(uid: String) = uid(JsonField.of(uid))

        /**
         * Sets [Builder.uid] to an arbitrary JSON value.
         *
         * You should usually call [Builder.uid] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun uid(uid: JsonField<String>) = apply { this.uid = uid }

        fun name(name: String) = name(JsonField.of(name))

        /**
         * Sets [Builder.name] to an arbitrary JSON value.
         *
         * You should usually call [Builder.name] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun name(name: JsonField<String>) = apply { this.name = name }

        fun imageUri(imageUri: String) = imageUri(JsonField.of(imageUri))

        /**
         * Sets [Builder.imageUri] to an arbitrary JSON value.
         *
         * You should usually call [Builder.imageUri] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun imageUri(imageUri: JsonField<String>) = apply { this.imageUri = imageUri }

        fun slug(slug: String) = slug(JsonField.of(slug))

        /**
         * Sets [Builder.slug] to an arbitrary JSON value.
         *
         * You should usually call [Builder.slug] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun slug(slug: JsonField<String>) = apply { this.slug = slug }

        fun theme(theme: String) = theme(JsonField.of(theme))

        /**
         * Sets [Builder.theme] to an arbitrary JSON value.
         *
         * You should usually call [Builder.theme] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun theme(theme: JsonField<String>) = apply { this.theme = theme }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [TeamListResponse].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .uid()
         * .name()
         * .slug()
         * .theme()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): TeamListResponse =
            TeamListResponse(
                checkRequired("uid", uid),
                checkRequired("name", name),
                imageUri,
                checkRequired("slug", slug),
                checkRequired("theme", theme),
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws ScalarInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): TeamListResponse = apply {
        if (validated) {
            return@apply
        }

        uid()
        name()
        imageUri()
        slug()
        theme()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: ScalarInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (uid.asKnown().isPresent) 1 else 0) +
            (if (name.asKnown().isPresent) 1 else 0) +
            (if (imageUri.asKnown().isPresent) 1 else 0) +
            (if (slug.asKnown().isPresent) 1 else 0) +
            (if (theme.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is TeamListResponse &&
            uid == other.uid &&
            name == other.name &&
            imageUri == other.imageUri &&
            slug == other.slug &&
            theme == other.theme &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(uid, name, imageUri, slug, theme, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "TeamListResponse{uid=$uid, name=$name, imageUri=$imageUri, slug=$slug, theme=$theme, additionalProperties=$additionalProperties}"
}
