// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async.sdks

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.sdks.repositories.RepositoryLinkParams
import com.scalar.models.sdks.repositories.RepositoryLinkResponse
import com.scalar.models.sdks.repositories.RepositoryUnlinkParams
import com.scalar.models.sdks.repositories.RepositoryUpdatePublishingParams
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

/** SDKs */
interface RepositoryServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): RepositoryServiceAsync

    /** Link one language target to a GitHub repository, so builds sync there. */
    fun link(uid: String, params: RepositoryLinkParams): CompletableFuture<RepositoryLinkResponse> =
        link(uid, params, RequestOptions.none())

    /** @see link */
    fun link(
        uid: String,
        params: RepositoryLinkParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<RepositoryLinkResponse> =
        link(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see link */
    fun link(
        params: RepositoryLinkParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<RepositoryLinkResponse>

    /** @see link */
    fun link(params: RepositoryLinkParams): CompletableFuture<RepositoryLinkResponse> =
        link(params, RequestOptions.none())

    /** Unlink one language target from its repository. */
    fun unlink(
        language: RepositoryUnlinkParams.Language,
        params: RepositoryUnlinkParams,
    ): CompletableFuture<Any?> = unlink(language, params, RequestOptions.none())

    /** @see unlink */
    fun unlink(
        language: RepositoryUnlinkParams.Language,
        params: RepositoryUnlinkParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> =
        unlink(params.toBuilder().language(language).build(), requestOptions)

    /** @see unlink */
    fun unlink(
        params: RepositoryUnlinkParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see unlink */
    fun unlink(params: RepositoryUnlinkParams): CompletableFuture<Any?> =
        unlink(params, RequestOptions.none())

    /** Toggle publish-on-merge and the release settings for a linked target. */
    fun updatePublishing(
        language: RepositoryUpdatePublishingParams.Language,
        params: RepositoryUpdatePublishingParams,
    ): CompletableFuture<Any?> = updatePublishing(language, params, RequestOptions.none())

    /** @see updatePublishing */
    fun updatePublishing(
        language: RepositoryUpdatePublishingParams.Language,
        params: RepositoryUpdatePublishingParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> =
        updatePublishing(params.toBuilder().language(language).build(), requestOptions)

    /** @see updatePublishing */
    fun updatePublishing(
        params: RepositoryUpdatePublishingParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see updatePublishing */
    fun updatePublishing(params: RepositoryUpdatePublishingParams): CompletableFuture<Any?> =
        updatePublishing(params, RequestOptions.none())

    /**
     * A view of [RepositoryServiceAsync] that provides access to raw HTTP responses for each
     * method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): RepositoryServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/sdks/{uid}/repositories`, but is otherwise the
         * same as [RepositoryServiceAsync.link].
         */
        fun link(
            uid: String,
            params: RepositoryLinkParams,
        ): CompletableFuture<HttpResponseFor<RepositoryLinkResponse>> =
            link(uid, params, RequestOptions.none())

        /** @see link */
        fun link(
            uid: String,
            params: RepositoryLinkParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<RepositoryLinkResponse>> =
            link(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see link */
        fun link(
            params: RepositoryLinkParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<RepositoryLinkResponse>>

        /** @see link */
        fun link(
            params: RepositoryLinkParams
        ): CompletableFuture<HttpResponseFor<RepositoryLinkResponse>> =
            link(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `delete /v1/sdks/{uid}/repositories/{language}`, but is
         * otherwise the same as [RepositoryServiceAsync.unlink].
         */
        fun unlink(
            language: RepositoryUnlinkParams.Language,
            params: RepositoryUnlinkParams,
        ): CompletableFuture<HttpResponseFor<Any?>> =
            unlink(language, params, RequestOptions.none())

        /** @see unlink */
        fun unlink(
            language: RepositoryUnlinkParams.Language,
            params: RepositoryUnlinkParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            unlink(params.toBuilder().language(language).build(), requestOptions)

        /** @see unlink */
        fun unlink(
            params: RepositoryUnlinkParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see unlink */
        fun unlink(params: RepositoryUnlinkParams): CompletableFuture<HttpResponseFor<Any?>> =
            unlink(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `post /v1/sdks/{uid}/repositories/{language}/publishing`,
         * but is otherwise the same as [RepositoryServiceAsync.updatePublishing].
         */
        fun updatePublishing(
            language: RepositoryUpdatePublishingParams.Language,
            params: RepositoryUpdatePublishingParams,
        ): CompletableFuture<HttpResponseFor<Any?>> =
            updatePublishing(language, params, RequestOptions.none())

        /** @see updatePublishing */
        fun updatePublishing(
            language: RepositoryUpdatePublishingParams.Language,
            params: RepositoryUpdatePublishingParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            updatePublishing(params.toBuilder().language(language).build(), requestOptions)

        /** @see updatePublishing */
        fun updatePublishing(
            params: RepositoryUpdatePublishingParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see updatePublishing */
        fun updatePublishing(
            params: RepositoryUpdatePublishingParams
        ): CompletableFuture<HttpResponseFor<Any?>> =
            updatePublishing(params, RequestOptions.none())
    }
}
