// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.scalar.services.async.teams

import com.scalar.core.ClientOptions
import com.scalar.core.RequestOptions
import com.scalar.core.http.HttpResponseFor
import com.scalar.models.teams.members.MemberDeleteParams
import com.scalar.models.teams.members.MemberListParams
import com.scalar.models.teams.members.MemberListResponse
import com.scalar.models.teams.members.MemberUpdateParams
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

/** Teams */
interface MemberServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): MemberServiceAsync

    /** Change what a member of the current team is allowed to do. */
    fun update(uid: String, params: MemberUpdateParams): CompletableFuture<Any?> =
        update(uid, params, RequestOptions.none())

    /** @see update */
    fun update(
        uid: String,
        params: MemberUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> = update(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see update */
    fun update(
        params: MemberUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see update */
    fun update(params: MemberUpdateParams): CompletableFuture<Any?> =
        update(params, RequestOptions.none())

    /** List the members of the current team, along with the invites still outstanding. */
    fun list(): CompletableFuture<MemberListResponse> = list(MemberListParams.none())

    /** @see list */
    fun list(
        params: MemberListParams = MemberListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<MemberListResponse>

    /** @see list */
    fun list(params: MemberListParams): CompletableFuture<MemberListResponse> =
        list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): CompletableFuture<MemberListResponse> =
        list(MemberListParams.none(), requestOptions)

    /** Remove someone from the current team. */
    fun delete(uid: String): CompletableFuture<Any?> = delete(uid, MemberDeleteParams.none())

    /** @see delete */
    fun delete(
        uid: String,
        params: MemberDeleteParams = MemberDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?> = delete(params.toBuilder().uid(uid).build(), requestOptions)

    /** @see delete */
    fun delete(uid: String, params: MemberDeleteParams): CompletableFuture<Any?> =
        delete(uid, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: MemberDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Any?>

    /** @see delete */
    fun delete(params: MemberDeleteParams): CompletableFuture<Any?> =
        delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(uid: String, requestOptions: RequestOptions): CompletableFuture<Any?> =
        delete(uid, MemberDeleteParams.none(), requestOptions)

    /**
     * A view of [MemberServiceAsync] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): MemberServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `patch /v1/teams/members/{uid}`, but is otherwise the
         * same as [MemberServiceAsync.update].
         */
        fun update(
            uid: String,
            params: MemberUpdateParams,
        ): CompletableFuture<HttpResponseFor<Any?>> = update(uid, params, RequestOptions.none())

        /** @see update */
        fun update(
            uid: String,
            params: MemberUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            update(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see update */
        fun update(
            params: MemberUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see update */
        fun update(params: MemberUpdateParams): CompletableFuture<HttpResponseFor<Any?>> =
            update(params, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `get /v1/teams/members`, but is otherwise the same as
         * [MemberServiceAsync.list].
         */
        fun list(): CompletableFuture<HttpResponseFor<MemberListResponse>> =
            list(MemberListParams.none())

        /** @see list */
        fun list(
            params: MemberListParams = MemberListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<MemberListResponse>>

        /** @see list */
        fun list(params: MemberListParams): CompletableFuture<HttpResponseFor<MemberListResponse>> =
            list(params, RequestOptions.none())

        /** @see list */
        fun list(
            requestOptions: RequestOptions
        ): CompletableFuture<HttpResponseFor<MemberListResponse>> =
            list(MemberListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/teams/members/{uid}`, but is otherwise the
         * same as [MemberServiceAsync.delete].
         */
        fun delete(uid: String): CompletableFuture<HttpResponseFor<Any?>> =
            delete(uid, MemberDeleteParams.none())

        /** @see delete */
        fun delete(
            uid: String,
            params: MemberDeleteParams = MemberDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params.toBuilder().uid(uid).build(), requestOptions)

        /** @see delete */
        fun delete(
            uid: String,
            params: MemberDeleteParams,
        ): CompletableFuture<HttpResponseFor<Any?>> = delete(uid, params, RequestOptions.none())

        /** @see delete */
        fun delete(
            params: MemberDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<Any?>>

        /** @see delete */
        fun delete(params: MemberDeleteParams): CompletableFuture<HttpResponseFor<Any?>> =
            delete(params, RequestOptions.none())

        /** @see delete */
        fun delete(
            uid: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<Any?>> =
            delete(uid, MemberDeleteParams.none(), requestOptions)
    }
}
